### ISSUE TITLE
Add csv metadata export

### ISSUE THREAD

**Issue by CTDragon** [DIGITALCRIMINAL/UltimaScraper#1053]
I've been locally maintaining version 5.3 for quite a while now so I could just get the csv files and use my own downlaoder. Recently it broke again with "user not found" during auth. It seems silly to keep maintaining this separately. I don't suppose we could add the csv export back to the main project could we???

**Comment by CTDragon** [comment]
A couple thoughts

If this is too much to ask, I could probably just query the sqlite database and generate it myself. 

Is there currently a way to turn off downloading of media? The `-m` flag no longer seems to work for that.

**Comment by DIGITALCRIMINAL** [comment]
> A couple thoughts
> 
> If this is too much to ask, I could probably just query the sqlite database and generate it myself.
Best if you just do this
> Is there currently a way to turn off downloading of media? The `-m` flag no longer seems to work for that.
Not yet

**Comment by CTDragon** [comment]
I went ahead and added the functionality directly into code in a local branch controlled by a parameter in the config defaulted to false. Do you want me to make a PR for it? 

If you'd rather not have it in there I can just merge/ rebase to your latest locally anytime I need an update.

**Comment by dilemmax** [comment]
> I went ahead and added the functionality directly into code in a local branch controlled by a parameter in the config defaulted to false. Do you want me to make a PR for it?
> 
> If you'd rather not have it in there I can just merge/ rebase to your latest locally anytime I need an update.

@CTDragon Is there any chance I can have a copy of this code? I miss exporting to CSV. I was using v6.0 until it stopped working for me as well.

**Comment by DIGITALCRIMINAL** [comment]
> I went ahead and added the functionality directly into code in a local branch controlled by a parameter in the config defaulted to false. Do you want me to make a PR for it?
> 
> If you'd rather not have it in there I can just merge/ rebase to your latest locally anytime I need an update.

Which functionality

**Comment by CTDragon** [comment]
> > I went ahead and added the functionality directly into code in a local branch controlled by a parameter in the config defaulted to false. Do you want me to make a PR for it?
> > If you'd rather not have it in there I can just merge/ rebase to your latest locally anytime I need an update.
> 
> @CTDragon Is there any chance I can have a copy of this code? I miss exporting to CSV. I was using v6.0 until it stopped working for me as well.

Sure thing

**Comment by CTDragon** [comment]
> > I went ahead and added the functionality directly into code in a local branch controlled by a parameter in the config defaulted to false. Do you want me to make a PR for it?
> > If you'd rather not have it in there I can just merge/ rebase to your latest locally anytime I need an update.
> 
> @CTDragon Is there any chance I can have a copy of this code? I miss exporting to CSV. I was using v6.0 until it stopped working for me as well.

I created a PR with the changes so it may end up in the main project if accepted. If not/ until then, you can grab it from here. Just hit Code->Download Zip. 

https://github.com/CTDragon/OnlyFans/tree/csv-export

![image](https://user-images.githubusercontent.com/5723697/116133434-b6634480-a69c-11eb-8247-71fe6a09669d.png)

**Comment by CTDragon** [comment]
Completely understandable. I'll keep it forked and will maintain it for my own use.

For anyone who needs it, @dilemmax, I'll try to keep a working release, but I can't promise it will always be up-to-date. It's working for me right now though.

Look for the csv releases on the following page.
https://github.com/CTDragon/OnlyFans/releases

**Comment by DIGITALCRIMINAL** [comment]
Actually, I'll incorporate your fork soon but change it up since it's only exporting links.

**Comment by nappyapp** [comment]
> > > I went ahead and added the functionality directly into code in a local branch controlled by a parameter in the config defaulted to false. Do you want me to make a PR for it?
> > > If you'd rather not have it in there I can just merge/ rebase to your latest locally anytime I need an update.
> > 
> > 
> > @CTDragon Is there any chance I can have a copy of this code? I miss exporting to CSV. I was using v6.0 until it stopped working for me as well.
> 
> Sure thing

Can I get a copy also?

**Comment by CTDragon** [comment]
The latest merge seems like a nightmare. All we want is a newline delimited list of links for each creator. Is this possible?

**Comment by DIGITALCRIMINAL** [comment]
> The latest merge seems like a nightmare. All we want is a newline delimited list of links for each creator. Is this possible?

As a text file? Sure.
