### ISSUE TITLE
[REQUEST] Add API Documentation / Examples

### ISSUE THREAD

**Issue by LunarPenguin** [DIGITALCRIMINAL/UltimaScraper#1371]
Hello,

An API has been added in recent commits which is great and i am thankful for but after the API rewrite i cant figure out how to import the new API library as the old import `apis.onlyfans.onlyfans as OnlyFans` gives a `ImportError: cannot import name 'create_auth' from partially initialized module 'apis.onlyfans.classes.create_auth' (most likely due to a circular import)` error.

I think it would be a good idea to add an API section to the README (or perhaps use the GitHub wiki function) explaining how to import the apis and explaining the endpoints available. Perhaps a couple example files could also be included

**Comment by DIGITALCRIMINAL** [comment]
Yeah I'm planning to do a wiki, but the script isn't finished or production ready yet. 

That circular import issue is annoying I had to to a few work arounds.

The way I'm importing it is:

`import api.onlyfans.onlyfans as OnlyFans`

**Comment by LunarPenguin** [comment]
> The way I'm importing it is:
> 
> import api.onlyfans.onlyfans as OnlyFans

Ok i will try that method instead and see if it works that way

> Yeah I'm planning to do a wiki, but the script isn't finished or production ready yet.

That good to hear, i myself use it for a couple helper/convenience scripts so its not that big of a deal if it breaks but its nice to have available anyway

**Comment by DIGITALCRIMINAL** [comment]
I've found a bypass.

You need to import main_helper from the helpers folder before you import the API.

You'll also need to copy and add these folders to your project:

apis, classes, database and helpers.

**Comment by LunarPenguin** [comment]
> You need to import main_helper from the helpers folder before you import the API.

this has successfully fixed the circular import but i'm now getting the following error: ```RuntimeWarning: coroutine 'create_auth.login' was never awaited authed.login(guest=True)``` when i call `authed.login(guest=True)`

**Comment by DIGITALCRIMINAL** [comment]
The API uses asyncio syntax now

**Comment by LunarPenguin** [comment]
> The API uses asyncio syntax now

I had seen that in the commit history but assumed that it would not impact my use of the API but apparently it did.

I have now rewritten my script to use asyncio.

**Comment by DIGITALCRIMINAL** [comment]
I've fixed circular imports now.

You can just use `from apis.onlyfans import onlyfans` to import the api and you don't need anything else.

**Comment by LunarPenguin** [comment]
That's good to hear. i will test it out soon
