### ISSUE TITLE
python-socks not compatible with latest python3.9

### ISSUE THREAD

**Issue by taux1c** [DIGITALCRIMINAL/UltimaScraper#1384]
I may have just caught this right after a python3.9.5 update and before a python-socks update but as it stands currently the latest python3.9 doesn't support python-socks. You just get a module not found when you try to import it in apis/api_helper.py

I checked to be sure I am using the latest version and tried importing with older versions and it works fine.

**Comment by qpidcock** [comment]
socketserver works with 3.9.5 & may be a viable alternative.

**Comment by LunarPenguin** [comment]
i just checked the `requirements.txt` file and that says the scraper uses uses `PySocks` not `python-socks`. So to me this seems like a non issue as long as `PySocks` supports `3.9`

**Comment by DIGITALCRIMINAL** [comment]
It works for me. I'm using socks5 proxies.

**Comment by qpidcock** [comment]
Weird, I cloned the repo and ran pip3 install --upgrade -r requirements.txt then rant the ofd_start.py (whatever is in the directions) and it gave me the stack trace telling me python-socks wasn't found (as stated above).

I should note that I rant this on a clean linode I created just for this.

Was there something I missed?

**Comment by LunarPenguin** [comment]
> Weird, I cloned the repo and ran pip3 install --upgrade -r requirements.txt

That's weird. i would recommend you run `pip list` or `pip freeze` to see which libraries and which versions of those libraries are installed and cross reference these with the contents of the `requirements.txt` file and install any requirements not already installed.

**Comment by drobb0690** [comment]
im getting the same issue, 

Traceback (most recent call last):
  File "G:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "G:\OnlyFans-master\OnlyFans-master\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "G:\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 1, in <module>
    from apis import api_helper
  File "G:\OnlyFans-master\OnlyFans-master\apis\api_helper.py", line 17, in <module>
    import python_socks
ModuleNotFoundError: No module named 'python_socks'

**Comment by qpidcock** [comment]
> 
> 
> i just checked the `requirements.txt` file and that says the scraper uses uses `PySocks` not `python-socks`. So to me this seems like a non issue as long as `PySocks` supports `3.9`

If you would reference the mentioned files and lines you would perhaps change your opinion. 

Check line 17 in apis/api_helper.py

**Comment by qpidcock** [comment]
> 
> 
> > Weird, I cloned the repo and ran pip3 install --upgrade -r requirements.txt
> 
> That's weird. i would recommend you run `pip list` or `pip freeze` to see which libraries and which versions of those libraries are installed and cross reference these with the contents of the `requirements.txt` file and install any requirements not already installed.

Yeah that was the first thing I did.  As mentioned though python-socks is required as per line 17 of apis/api_helper.py and python-socks doesn't work with 3.9.5 but I am off today and I am going to take a look at the whole thing and see if it needs to have that file changed to use pysocks or if it cuts holes in the whole thing, etc.

**Comment by drobb0690** [comment]
i had this same issue and i ran
pip install --upgrade --user -r requirements.txt
and that seemed to solve it

**Comment by qpidcock** [comment]
> 
> 
> i had this same issue and i ran
> pip install --upgrade --user -r requirements.txt
> and that seemed to solve it

Ah, glad it helped. I just tried it and unfortunately; for me it just says everything meets requirements. (It did update url libs) but same error still.

**Comment by qpidcock** [comment]
> 
> 
> i had this same issue and i ran
> pip install --upgrade --user -r requirements.txt
> and that seemed to solve it

What version of python are you using? I am on 3.9.5

**Comment by drobb0690** [comment]
> > i had this same issue and i ran
> > pip install --upgrade --user -r requirements.txt
> > and that seemed to solve it
> 
> What version of python are you using? I am on 3.9.5

I actually upgraded to 3.9.5 prior to even installing this release and before running the above command was getting the same issue as you.
