### ISSUE TITLE
purchased videos

### ISSUE THREAD

**Issue by Skided** [DIGITALCRIMINAL/UltimaScraper#1386]
it doesnt downlaod purchased content if you stopped the sub to the creator can you add option that it will?

**Comment by WellSomething** [comment]
I would've thought that `"scrape_paid_content": true` did that, or am I wrong?

**Comment by Skided** [comment]
no its not

**Comment by LunarPenguin** [comment]
i believe that the `"scrape_paid_content": true` option intents to download the all your purchased content but maybe that logic got broken by the most recent OF redesign. Maybe @DIGITALCRIMINAL can have a look at it again.

**Comment by DIGITALCRIMINAL** [comment]
I'm not subscribed to users that I've bought content off of and it downloads. Maybe the user has deleted their account?

**Comment by ThrowawayDane** [comment]
I can report the same issue, and i can also inform that one of the creators i did bought content off i bought 2 videos but the script do only download one of the 2 videos.

And i only have one creator that i did buy content from that have removed the account but i have a lot that i have bought from creators that are still on the platform. 

Is there any logs i can create to help you @DIGITALCRIMINAL solve this.

**Comment by 666diabolus** [comment]
> I'm not subscribed to users that I've bought content off of and it downloads. Maybe the user has deleted their account?

I can confirm when a creator delete their account, all of the contents purchased from OTHER creators BEFORE buying those content from the creator that delete the account, will be ignored, with or without `"scrape_paid_content"`

**Comment by exogenomic** [comment]
I'm also experiencing what I believe to be the same issue. When I view my list of purchased content, it doesn't match up with what gets scraped and downloaded. Everything older than a certain point (maybe when some other model I purchased from cancelled her account), doesn't get downloaded. Is there perhaps an issue where the code is supposed to skip a certain purchased item that's no longer available, but instead skips everything remaining in the list?
