### ISSUE TITLE
KeyError: 'author'

### ISSUE THREAD

**Issue by tocking** [DIGITALCRIMINAL/UltimaScraper#1419]
Running on latest Master copy...

Scrape Processing
Name: paxclusive
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "G:\OF2\OnlyFans-master\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "G:\OF2\OnlyFans-master\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "G:\OF2\OnlyFans-master\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "G:\OF2\OnlyFans-master\helpers\main_helper.py", line 921, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 159, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "G:\OF2\OnlyFans-master\modules\onlyfans.py", line 786, in prepare_scraper
    master_set += await subscription.get_archived_posts()
  File "G:\OF2\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 424, in get_archived_posts
    final_results = [create_post(x, self) for x in results if x]
  File "G:\OF2\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 424, in <listcomp>
    final_results = [create_post(x, self) for x in results if x]
  File "G:\OF2\OnlyFans-master\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'

**Comment by DIGITALCRIMINAL** [comment]
Does this happen every time?

**Comment by tocking** [comment]
With this model, yep.

**Comment by valdearg** [comment]
Not sure if this is related to the same error? I'm getting a similar one which is "KeyError: 'created_at'"

```Scrape Processing
Name: lysaretta
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1689.59it/s]
Processing metadata.
Merging new metadata with legacy metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "G:\Scripts\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "G:\Scripts\OnlyFans\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "G:\Scripts\OnlyFans\helpers\main_helper.py", line 921, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 159, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 833, in prepare_scraper
    await process_metadata(
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 657, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "G:\Scripts\OnlyFans\helpers\main_helper.py", line 564, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'```

**Comment by tocking** [comment]
Also getting the error with rhoneeandkhoa

**Comment by tocking** [comment]
Any updates on this? It's happening for more models

**Comment by DIGITALCRIMINAL** [comment]
Are you blocking them????

**Comment by tocking** [comment]
No, I'm subscribed to both and can see the contents in a browser.

**Comment by tocking** [comment]
I'm able to get around this by putting a try/except block around the lines where it fetches the posts (master_set = await subscription.get_posts()) , but this is obviously a bandaid solution.  Is there anything I can do to help diagnose the cause of this problem?

**Comment by neuri4848** [comment]
I found an older commit in my files from june 19 and that one worked for me. Dont know what the difference is between those tho

**Comment by tocking** [comment]
@DIGITALCRIMINAL  - anything I can do to help diagnose/debug this issue?  It's causing real problems with a few profiles I'm trying to scrape

**Comment by tocking** [comment]
Sure...where do you want me to put the print statement?

**Comment by DIGITALCRIMINAL** [comment]
Above self.author

**Comment by tocking** [comment]
{'responseType': 'post', 'id': 24256657, 'postedAt': '2020-05-19T13:13:43+00:00', 'postedAtPrecise': '1589894023.000000', 'isReportedByMe': True}

I think we had a similar issue before where it was a post I'd reported once upon a time...

**Comment by EightDee** [comment]
I'm getting the same issue with model lovegiavanna. Below is the options printout

```{'responseType': 'post', 'id': 47073760, 'postedAt': '2020-09-15T13:51:25+00:00', 'postedAtPrecise': '1600177885.000000', 'isReportedByMe': True}
{'responseType': 'post', 'id': 46583386, 'postedAt': '2020-09-15T13:51:24+00:00', 'postedAtPrecise': '1600177884.000000', 'isReportedByMe': True}```

**Comment by deadcode0815** [comment]
Having the same issue with rileyreidx3. But I actually don't know what to add the get the options printout for further debugging.

**Comment by pianonorte** [comment]
Quick and dirty fix/workaround:
Change line 395 of apis/api_helper.py to:
`    media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]
`

**Comment by naodrej** [comment]
> 
> 
> Quick and dirty fix/workaround:
> Change line 395 of apis/api_helper.py to:
> ` media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]`

Thank you for this workaround!

**Comment by Gixxa** [comment]
I had the same problem with a model that I subbed to for the first time.  The fix/workaround from @Charmoq worked for me.

@DIGITALCRIMINAL 

Could the fix from @Charmoq be used in the master or would something speak against it?

**Comment by porncritic** [comment]
@Charmoq thank you for workaround, it was only happening on only a few subs, but this seemed to fix it for those. Thanks again to everyone for your work!

**Comment by zymurnerd** [comment]
This is still an issue with the current commit in the master branch. The workaround proposed by @Charmoq works. Since this issue seems to be pervasive and is over a month old will this fix be pushed to the master branch soon?

**Comment by ChangeUsername** [comment]
Happens with free to subscribe user scarlett-ashe too. If this helps :)

**Comment by fg4jerem** [comment]
> This is still an issue with the current commit in the master branch. The workaround proposed by @Charmoq works. Since this issue seems to be pervasive and is over a month old will this fix be pushed to the master branch soon?

I doubt very much this is a proper solution, but only a workaround to skip the problematic content. Am I wrong?

I'm confused by the significance of the "isReportedByMe" attribute, as I've never reported any content or any user on OF.

**Comment by tocking** [comment]
@fg4jerem - what does it matter whether you've ever reported anybody?  Clearly people have, and it affects usage of this script.  The workaround works but it'd be great to not have to re-plumb this into the script after every update.

**Comment by fg4jerem** [comment]
@tocking There's a 2 weeks old PR already: https://github.com/DIGITALCRIMINAL/OnlyFans/pull/1593. The change is even approved! All that is missing is for someone with write access to action the merge. I agree with you that merging a workaround is a good temporary solution while waiting for the real solution. I never disputed that. I only meant to say a workaround is not a fix. Hence it wouldn't fix the issue you reported, only hide it for the time being.

Since a workaround exists, this discussion thread should be about the real issue and a potential real fix at this point. Alas that was my assumption and thinking when writing my comment above.

>  what does it matter whether you've ever reported anybody?

Because my interpretation of an attribute named "...ByMe" should mean I'm the one who reported it and not someone else. At least that's my interpretation. But I could be wrong too. How do you know what this attribute means? How is that so "clearly" it? Are you the software developper working at OnlyFans who designed this feature? Personally I have no idea how this attribute matters or how it comes into play here crashing the scrapping with a missing "author" key. I was mearly asking a question, fishing and hoping anyone in this thread had more information or had reversed-engineered it. Notice I didn't mention you specifically in that comment. I'm sorry for trying to feed into the discussion hoping it would generate ideas or provoke new thoughts. I never imagined this would offend you.

**Comment by tocking** [comment]
The attribute indicates a post that the user (ie “me”) has reported at some point in the past - whether intentionally or not. You can verify by going to the URL of the post that crashes the script, and you’ll get a “Thanks for reporting this!” style page.

**Comment by vfrxart** [comment]
hm, i tried changing that stuff on line 395 & get this error.

> File "E:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
>     loop.run_until_complete(main())
>   File "C:\Users\on3si\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "E:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\start_ofd.py", line 44, in main
>     api = await main_datascraper.start_datascraper(
>   File "E:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 93, in start_datascraper
>     await main_helper.process_names(
>   File "E:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\helpers\main_helper.py", line 939, in process_names
>     result = await module.start_datascraper(authed, username, site_name)
>   File "E:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\modules\onlyfans.py", line 160, in start_datascraper
>     await prepare_scraper(authed, site_name, item)
>   File "E:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\modules\onlyfans.py", line 823, in prepare_scraper
>     unrefined_set = await tqdm.gather(tasks, **settings)
>   File "C:\Users\on3si\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 79, in gather
>     res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
>   File "C:\Users\on3si\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
>     res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
>   File "C:\Users\on3si\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 614, in _wait_for_one
>     return f.result()  # May raise f.exception().
>   File "C:\Users\on3si\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
>     return i, await f
> TypeError: object list can't be used in 'await' expression
> 
> 
> 
>

**Comment by IT6uru** [comment]
> 
> 
> hm, i tried changing that stuff on line 395 & get this error.
> 
> > File "E:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\start_ofd.py", line 60, in 
> > loop.run_until_complete(main())
> > File "C:\Users\on3si\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
> > return future.result()
> > File "E:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\start_ofd.py", line 44, in main
> > api = await main_datascraper.start_datascraper(
> > File "E:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 93, in start_datascraper
> > await main_helper.process_names(
> > File "E:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\helpers\main_helper.py", line 939, in process_names
> > result = await module.start_datascraper(authed, username, site_name)
> > File "E:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\modules\onlyfans.py", line 160, in start_datascraper
> > await prepare_scraper(authed, site_name, item)
> > File "E:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\modules\onlyfans.py", line 823, in prepare_scraper
> > unrefined_set = await tqdm.gather(tasks, **settings)
> > File "C:\Users\on3si\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 79, in gather
> > res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
> > File "C:\Users\on3si\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 79, in 
> > res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
> > File "C:\Users\on3si\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 614, in _wait_for_one
> > return f.result()  # May raise f.exception().
> > File "C:\Users\on3si\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
> > return i, await f
> > TypeError: object list can't be used in 'await' expression

Same here.

**Comment by IT6uru** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans

Fixed here
