### ISSUE TITLE
Blacklist_name only working for the first username in a list.

### ISSUE THREAD

**Issue by zeldatp151** [DIGITALCRIMINAL/UltimaScraper#1451]
I created a list on OF, simply titled "ignore" to use as a blacklist for accounts that seem to break the script every time it reaches them, and added "ignore" to blacklist_name in the config. But for some reason, only the first account I add to "ignore" actually gets blacklisted. I created a second blacklist, and added a different account first and tried again, same result. only the first accounts is actually blacklisted, the rest in the list get scraped.

**Comment by LunarPenguin** [comment]
I had this problem some time ago but an update seemed to have fixed it. so i would recommend updating the scraper

**Comment by zeldatp151** [comment]
I'm running the latest release 7.4, that's when the problem started.

**Comment by DIGITALCRIMINAL** [comment]
Try latest commit
