### ISSUE TITLE
How are subscriptions sorted? [possible enhancement]

### ISSUE THREAD

**Issue by ghost** [DIGITALCRIMINAL/UltimaScraper#1464]
So I was just wondering how are subscriptions sorted? Especially if someone is subscribed to many creators it can be a bit difficult to find the model you are looking for.

I feel like there is no real pattern there. So my suggestion would be a setting where we can decide to have them listet via alphabet (A-Z or Z-A), by expire date (if the API gives that information) or any other useful way for sorting a list.

**Comment by DIGITALCRIMINAL** [comment]
By expiration date
