### ISSUE TITLE
[REQUEST/ENHANCEMENT] Add model id to the formatting options

### ISSUE THREAD

**Issue by LunarPenguin** [DIGITALCRIMINAL/UltimaScraper#1471]
I just noticed that a model that i follow has changed her username from `loralvova` to `baby_lon` but both usernames still point to the same account and user id but the script has now downloaded the model twice.

Being able to use the model id would enable me to account for models changing their usernames and causing duplicate files.

If this is already a thing but i couldn't find it please let me know and i will close this issue

**Comment by Gixxa** [comment]
I just cut and paste all the files from the old name to the new one. Should be doable for every user. I also recommend using something like CloneSpy to sort out dups.

**Comment by LunarPenguin** [comment]
> I just cut and paste all the files from the old name to the new one. Should be doable for every user.

I don't doubt that that is a good workaround but i opened this is issue to highlight imo an oversight in the program and suggest a way to fix said problem. 

you or i might not have a lot of models to scrape but some users of this program do and it would be cumbersome for them to perform this workaround manually when it can be fixed with a small change in the code.

If i can get around to it i will probably try to fix it myself and submit a Pull Request if DC is to busy to get around to it himself
