### ISSUE TITLE
the auth file is empty after AD

### ISSUE THREAD

**Issue by lucky1luc** [DIGITALCRIMINAL/UltimaScraper#1479]
After Access Denied the auth file is empty 
C:\Data\OnlyFans-7.4>python start_ofd.py
Site: 0 = onlyfans |
0
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Traceback (most recent call last):
  File "C:\Data\OnlyFans-7.4\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Data\OnlyFans-7.4\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Data\OnlyFans-7.4\datascraper\main_datascraper.py", line 88, in start_datascraper
    main_helper.export_data(auth_details, user_auth_filepath)
  File "C:\Data\OnlyFans-7.4\helpers\main_helper.py", line 771, in export_data
    ujson.dump(metadata, outfile, indent=2, escape_forward_slashes=False)
TypeError: <apis.onlyfans.classes.extras.cookie_parser object at 0x000002B2D3A47B80> is not JSON serializable

and then I have a zero bytes auth file
and my webbrowswer session is logged out

**Comment by LunarPenguin** [comment]
I do not know what caused this issue but deleting the `auth.json` file and then running the program should generate a new `auth.json` file. after that follow the auth instructions in the `readme.md`

Maybe @DIGITALCRIMINAL can have a look at this error.

**Comment by lucky1luc** [comment]
I know that Thanks. I have one more strange thing that I found. When following the auth.json documentation using the cookie from Firefox caused access denied, but the same Instruction with Edge works. Maybe the cookie parsing is a bit skewed towards one web browser?

**Comment by LunarPenguin** [comment]
> using the cookie from Firefox caused access denied, but the same Instruction with Edge works. Maybe the cookie parsing is a bit skewed towards one web browser?

That's strange, i needed to replace my cookie on Friday due to a firefox update and everything went fine for me.
