### ISSUE TITLE
Login via Web Browser

### ISSUE THREAD

**Issue by americanseeder1865** [DIGITALCRIMINAL/UltimaScraper#1489]
In [start_ofl.py](https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/extras/OFLogin/start_ofl.py), in login(), The script fails because OnlyFans has randomized Attribute ID's, among other issues. I am working on a pull request. I will detail all of what I did to get this working in that Pull Request. This happens in Docker.

Can you assign this to me?

**Comment by americanseeder1865** [comment]
@DIGITALCRIMINAL This ended up being quite a challenge to make things work headlessly in a docker container and I am not done yet. Do you want me to submit a pull request that should work for people with GUI's or wait until I am done getting all of it to work headlessly? I might appreciate some insight too.

**Comment by DIGITALCRIMINAL** [comment]
I don't know what you mean by random attributes

**Comment by americanseeder1865** [comment]
This is Refresh One
![Capture1](https://user-images.githubusercontent.com/87628702/126156957-386089d3-ec13-4262-ac89-8797b56db1e1.PNG)
and this is refresh two 
![Capture2](https://user-images.githubusercontent.com/87628702/126157000-3036ce66-e0e9-42cc-9ab3-86dc482a0714.PNG)

This is what I mean.

**Comment by DIGITALCRIMINAL** [comment]
Ohhh that, I forgot about logging in via the browser. You can push it when it's headless. 
Less GUI is better and thank you for the work 👍🏽
