### ISSUE TITLE
Missing Posts issue has come up again.

### ISSUE THREAD

**Issue by americanseeder1865** [DIGITALCRIMINAL/UltimaScraper#1493]
I am currently on commit 79b0ad180aae407c495fa6c971517847229a4674. The infinite missing posts issue is happening again. #1118

**Comment by naodrej** [comment]
I'm having the same issue. I tried adding the profiles it's happening on to the blacklist but it only ignores the first profile on the list. I notice it is happening to profiles that have expired on your subscriptions, but are still on the subscription list.

**Comment by Gamma-Velorum** [comment]
> I notice it is happening to profiles that have expired on your subscriptions, but are still on the subscription list.

Having the same problem.

**Comment by WellSomething** [comment]
> > I notice it is happening to profiles that have expired on your subscriptions, but are still on the subscription list.
> 
> Having the same problem.

Yep, that's what it is. And I keep needing to create new Lists to ignore models since old lists get ignored for some reason. Seems like OF takes a lot time to recognize that there's a different model now in the list to be ignored and as a consequence the script doesn't pick it up either, so the solution is to make a new list for the new model I want to blacklist (temporarily until OF finally recognizes I'm not subbed any longer either)

**Comment by DIGITALCRIMINAL** [comment]
Which models do these effect? The issue usually goes away

**Comment by WellSomething** [comment]
> Which models do these effect? The issue usually goes away

This began a few days ago, it seemed like the models (at least some) are being kept on the list longer than usual even though when you visit their OF page it says expired a day ago (maybe even 2 days ago) and don't have access to their posts. Here's one that had an issue a few days ago when it ended: noeliaofficial. For some reason they're also at the top of your script when this happens, so they're the first model it tries to scrape.

**Comment by Gixxa** [comment]
I also have this issue since a few minutes ago. However I'm still subbed until Aug 10th 2022. I put the model on a blacklist for now and with that the scraper works again. I'l update to the latest master and see if it still does not work.

**Comment by DIGITALCRIMINAL** [comment]
Yeah I wouldn't know how to fix it unless I use someone's account

**Comment by Gixxa** [comment]
Not sure if it helps but here is a 12 month free sub for the model in question for me:

https://onlyfans.com/action/trial/cmoc5ubnsu442lzaepriohzhlrvwc5w8

**Comment by americanseeder1865** [comment]
@DIGITALCRIMINAL I was thinking about making this more verbose anyway. My next thing I want to do after my assigned headless task is to get some easier ways to actually install (probably using make or something) and then write better documentation.

**Comment by naodrej** [comment]
I don't think you actually have to fix the issue, but maybe fix the work around with the blacklist. Since right now, the blacklist seems to only ignore the first name on the list, and the problem persists if the account has multiple subs that expired but not yet removed on onlyfans end.

**Comment by WellSomething** [comment]
> I don't think you actually have to fix the issue, but maybe fix the work around with the blacklist. Since right now, the blacklist seems to only ignore the first name on the list, and the problem persists if the account has multiple subs that expired but not yet removed on onlyfans end.

I agree with this. I haven't tested the newest versions, I'm still using the 6/20/21 Master or such, but a blacklist function that works properly would more worth it. One is what you mention of the first model in the list, the second it seems like that list gets "cached" somehow on the site. Like say I want to change the model, in the blacklist it doesn't register it until much later, so I would need to actually create a new list for this new model I want to ignore instead. I think those improvements would help more than fixing the issue found here.
