### ISSUE TITLE
Working on Fix: New Dockerfile breaks Bind Mounts.

### ISSUE THREAD

**Issue by americanseeder1865** [DIGITALCRIMINAL/UltimaScraper#1498]
While Commit 79b0ad180aae407c495fa6c971517847229a4674 is super cool and makes docker very secure, it breaks bind mounts due to permission issues. I will be coming up with a fix for this in a bit unless someone beats me to it. Attn: @DIGITALCRIMINAL @adamvorobyov

**Comment by americanseeder1865** [comment]
update: I will also pull submit a seperate pull request to update documentation for [README.md](https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/README.md) to update the command.

**Comment by E0911CD45B19686** [comment]
Moving the `cmd` out of the dockerfile and into [docker-compose.yml](https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/docker-compose.yaml#L15) is unnecessary and breaks non docker-compose usage.

Feel free to ping me for review, the recent changes also broke my docker usage.

**Comment by ud266** [comment]
The "fix" should be to just revert the changes. I made this comment https://github.com/DIGITALCRIMINAL/OnlyFans/pull/1491#issuecomment-883333097 saying basically the same thing.

- As @americanseeder1865 reports, the `USER` change chokes on permissions.
- As @E0911CD45B19686 reports, splitting the configuration between the Dockerfile and Compose file ruins running with `docker run`.
- The multi-stage build is entirely unnecessary.
- Installing the "required" packages is entirely unnecessary.
- And honestly, changing the `USER` is unnecessary and just makes things complicated for the user. An easier way to handle it would be to do it at runtime:
    ```
    --user $(id -u):$(id -g)
    ```
