### ISSUE TITLE
error in line 60, 642 and 41

### ISSUE THREAD

**Issue by lanzjose** [DIGITALCRIMINAL/UltimaScraper#1500]
Hey! i don't know if this could be related to me intalling windows 11, but i am getting this error...

Traceback (most recent call last):
  File "D:\Only\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Only\start_ofd.py", line 41, in main
    site_choice = int(site_choice)
ValueError: invalid literal for int() with base 10: ''

**Comment by DarkDownloader** [comment]
Rerun the command to install the requirements. If this is still an issue, and it worked before the Windows 11 upgrade, then you will need to revert back.

**Comment by Jar4ek** [comment]
I have the same problem :

**Comment by Shingotink** [comment]
I did what DarkDownloader said above and now it's working again.
Rerun the command to install the requirements.

pip install --upgrade --user -r requirements.txt

**Comment by Jar4ek** [comment]
Everything is installed and the error is the same.
