### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlalchemy'

### ISSUE THREAD

**Issue by nikko-guy** [DIGITALCRIMINAL/UltimaScraper#1524]
It's installed idk why it's giving me the error. Here's the full error:
Traceback (most recent call last):
  File "D:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "D:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "D:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\helpers\main_helper.py", line 1, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "D:\Downloads\OnlyFans-7.4.1\OnlyFans-7.4.1\database\databases\user_data\models\api_table.py", line 6, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by starrlord314** [comment]
Run "pip install -r requirements.txt"

**Comment by Dr-DaNk** [comment]
done that

**Comment by DarkDownloader** [comment]
I can't reproduce this. Make sure PIP is on the latest version and try again.

Are you using Windows 11?

**Comment by LunarPenguin** [comment]
Make sure you're installing SQLAlchemy in the same python version you're running the script on, make sure python is up to date and make sure the spelling of SQLAlchemy is correct.

**Comment by Dr-DaNk** [comment]
not using windows 11. Pip is up to date. using the SQLAlchemy version stated in requirements.txt

**Comment by LunarPenguin** [comment]
Have you checked if you've perhaps got multiple instances of Python installed?

**Comment by dwhitz** [comment]
As supposed by @LunarPenguin if you have multiple version of python you should check [this answer](https://stackoverflow.com/a/25123329/5533075)

The command will be something like
`python3.8 -m pip install foo`
