### ISSUE TITLE
Not sure of this issue - Errors in multiple lines  

### ISSUE THREAD

**Issue by ghost** [DIGITALCRIMINAL/UltimaScraper#1538]
Not sure what these line errors mean..I was able to use it just fine a few days ago, I didn't change anything and now I am getting these errors, anyone know what they can mean?

`
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "C:\Users\milkt\Desktop\OnlyFans-master1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\milkt\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\milkt\Desktop\OnlyFans-master1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\milkt\Desktop\OnlyFans-master1\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "C:\Users\milkt\Desktop\OnlyFans-master1\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\milkt\Desktop\OnlyFans-master1\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Users\milkt\Desktop\OnlyFans-master1\modules\onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "C:\Users\milkt\Desktop\OnlyFans-master1\apis\onlyfans\classes\create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "C:\Users\milkt\Desktop\OnlyFans-master1\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "C:\Users\milkt\Desktop\OnlyFans-master1\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'
`

**Comment by headphonia** [comment]
I'm also seeing the same issue, script ran fine this morning so OF must've done something to that broke it.

**Comment by LunarPenguin** [comment]
Im also seeing the same thing, about half of the models i follow are affected, 

OF indeed seems to have made a change somewhere. 
Maybe @DIGITALCRIMINAL has some time to look at the problem. 

@milktruckk could you change the title of this issue to something a little more descriptive of the error that your getting so that people can find it easier and hopefully we wont get a dozen identical issues.

**Comment by Pwnager12345** [comment]
Getting the same problem, though it is only happening with 2 out of the 10 or so I downloaded today.

**Comment by RuneDemomn** [comment]
I too am experiencing this issue on some account, while others are uneffected.
```
> Traceback (most recent call last):
>   File "C:\Users\User\Desktop\DIGITALCRIMINAL\start_ofd.py", line 60, in <module>
>     loop.run_until_complete(main())
>   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "C:\Users\User\Desktop\DIGITALCRIMINAL\start_ofd.py", line 44, in main
>     api = await main_datascraper.start_datascraper(
>   File "C:\Users\User\Desktop\DIGITALCRIMINAL\datascraper\main_datascraper.py", line 93, in start_datascraper
>     await main_helper.process_names(
>   File "C:\Users\User\Desktop\DIGITALCRIMINAL\helpers\main_helper.py", line 939, in process_names
>     result = await module.start_datascraper(authed, username, site_name)
>   File "C:\Users\User\Desktop\DIGITALCRIMINAL\modules\onlyfans.py", line 160, in start_datascraper
>     await prepare_scraper(authed, site_name, item)
>   File "C:\Users\User\Desktop\DIGITALCRIMINAL\modules\onlyfans.py", line 791, in prepare_scraper
>     master_set = await subscription.get_posts()
>   File "C:\Users\User\Desktop\DIGITALCRIMINAL\apis\onlyfans\classes\create_user.py", line 301, in get_posts
>     final_results = [create_post(x, self) for x in results]
>   File "C:\Users\User\Desktop\DIGITALCRIMINAL\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
>     final_results = [create_post(x, self) for x in results]
>   File "C:\Users\User\Desktop\DIGITALCRIMINAL\apis\onlyfans\classes\create_post.py", line 13, in __init__
>     self.author = create_user.create_user(option["author"])
> KeyError: 'author'
```

**Comment by simonchin513** [comment]
The workaround provided in other threads (different title but the exact some problem, don't understand why are people spamming new issues) is working.

**Comment by RuneDemomn** [comment]
This workaround worked for me https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231

**Comment by howdothiswork** [comment]
the workaround did not work for me

**Comment by Dered118** [comment]
That workaround works for me neither

**Comment by whiteprivilege** [comment]
Workaround didn't work for me either.
