### ISSUE TITLE
No longer able to log in via email and password

### ISSUE THREAD

**Issue by testarogue** [DIGITALCRIMINAL/UltimaScraper#1539]
Hi,

Unfortunately the auth_hash is not present in my network debugger (and hasnt been for a couple of months), so I have relied on authenticating using email and password.

Unfortunately after my last session has expired, I have not been able to get it to open a browser and prompt for manual recaptcha solving before logging in. Has this feature been discontinued or do I need to reset the state of the cloned content somehow?

Thanks

**Comment by americanseeder1865** [comment]
This has been broken for a bit. I am working on it. Please also review the new instructions.
