### ISSUE TITLE
don't know what to title this issue

### ISSUE THREAD

**Issue by J4k-The-Reaper** [DIGITALCRIMINAL/UltimaScraper#1548]
scraper was working great but then suddenly i got this error. anyone else have same issue or know what the problem is?

![Screenshot 2021-08-08 013508](https://user-images.githubusercontent.com/35021417/128626183-94a7901f-f835-4499-8e99-39eaa8b1451d.png)

**Comment by Jakeyy22** [comment]
Same issue as #1538 #1540

An easy fix for now has been posted on #1419

**Comment by paperboy11** [comment]
> Same issue as #1538 #1540
> 
> An easy fix for now has been posted on #1419

this has not been fixed, issue still remains on some models. @DIGITALCRIMINAL this is on going for many of us

**Comment by J4k-The-Reaper** [comment]
hopefully this gets fixed soon.... ;\
