### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by origsgkid** [DIGITALCRIMINAL/UltimaScraper#1563]
I couldn't find a link to donate to your open source effort. Any plans to provide a donation link or did I miss one?

**Comment by E0911CD45B19686** [comment]
> or did I miss one?

You can use [search](https://github.com/DIGITALCRIMINAL/OnlyFans/search?q=donate) to find links in https://github.com/DIGITALCRIMINAL/OnlyFans/issues/361
