### ISSUE TITLE
Stuck on   Site: 0 = onlyfans | 

### ISSUE THREAD

**Issue by LahaLuhem** [DIGITALCRIMINAL/UltimaScraper#1565]
Hi, I have a standard setup (nothing different from a straight default settings etc.)
When I just run it straight out (after the 2 initial setup wait-loops), it just gets stuck on
`Site: 0 = onlyfans | `

+ Using cookie-method for authentication
+ Windows host
+ Python version 3.9.5

Is it something wrong on my end maybe?

**Comment by LunarPenguin** [comment]
Have you typed in `0` and pressed <kbd>enter</kbd>? if so what happens?

**Comment by bigbluedeer** [comment]
There is something missing behind the |
`x = exit`

It first happened a while ago, do not know when

**Comment by mkmb1** [comment]
i think if you specify "auto_site_choice": "onlyfans" in auth.json it will work

**Comment by bigbluedeer** [comment]
Just set `"exit_on_completion": True` (maybe also `"infinite_loop": False`) in config.json
