### ISSUE TITLE
Suggestion - Local WebApp to see content just like OF

### ISSUE THREAD

**Issue by pnpninja** [DIGITALCRIMINAL/UltimaScraper#1567]
This is a suggestion - I'd love to read the titles and description etc. Can we work on this too?

**Comment by americanseeder1865** [comment]
You should already be able to. The application put it all into a database called user_data.db , you should just need an application to view the data.

**Comment by whateverman91** [comment]
Dup of https://github.com/DIGITALCRIMINAL/OnlyFans/issues/485 - maintainer doesn't seem interested

**Comment by pnpninja** [comment]
Its not like that.. Its hard to manually open DB and see the title and get correlated file location and open. I think it'll make a more enjoyable experience if there was a webapp that renders it nicely

**Comment by heltbill** [comment]
> Its not like that.. Its hard to manually open DB and see the title and get correlated file location and open. I think it'll make a more enjoyable experience if there was a webapp that renders it nicely

I'm using this web page to open the database file (.db) where all the metadata is stored.

https://sqliteonline.com/

![2021-08-19 (8)](https://user-images.githubusercontent.com/80179999/130154760-32176af8-d657-4b8d-9263-9b7f922287e1.jpg)

Once the database is open you execute SQL queries on the tables or export the tables in another format.
