### ISSUE TITLE
TypeError: 'coroutine' object is not iterable

### ISSUE THREAD

**Issue by Bulli** [DIGITALCRIMINAL/UltimaScraper#1576]
I have made an update to the latest version. When I start the script, it ends with this error.
However, I've made a revert to 1491 and it works fine as before.

(xxxxx = anonymized)

Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Welcome xxxxx | xxxxx 
Scraping Paid Content
Scraping - xxxxx | 1 / 9
Scraping - xxxxx | 2 / 9
Scraping - xxxxx | 3 / 9
Scraping - xxxxx | 4 / 9
Traceback (most recent call last):
  File "xxxx\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "xxxx\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "xxxx\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "xxxx\datascraper\main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "xxxx\modules\onlyfans.py", line 401, in paid_content_scraper
    unrefined_set = await tqdm.gather(*tasks, **settings)
  File "xxxx\Python39\lib\site-packages\tqdm\asyncio.py", line 74, in gather
    ifs = [wrap_awaitable(i, f) for i, f in enumerate(fs)]
TypeError: 'coroutine' object is not iterable

**Comment by brakheart** [comment]
having the exact same error here, also after updating to the latest version

**Comment by metalmau5** [comment]
+1 having this issue

**Comment by JWeavis** [comment]
+1 having this issue

**Comment by americanseeder1865** [comment]
-1 not having this issue. Lets take a look at some things. First what platform are you using? Windows, Linux, or Docker?

**Comment by Bulli** [comment]
Windows 10

**Comment by americanseeder1865** [comment]
alright. Does your requirements.txt look like this?

> requests
beautifulsoup4
urllib3
win32-setctime
python-socks[asyncio]
psutil
python-dateutil
lxml
mergedeep
jsonpickle
ujson
sqlalchemy==1.4.20
alembic
tqdm>=4.62.0
selenium
selenium-wire==2.1.2
user_agent
aiohttp
aiohttp_socks

**Comment by chibi624** [comment]
> 
> 
> alright. Does your requirements.txt look like this?
> 
> > requests
> > beautifulsoup4
> > urllib3
> > win32-setctime
> > python-socks[asyncio]
> > psutil
> > python-dateutil
> > lxml
> > mergedeep
> > jsonpickle
> > ujson
> > sqlalchemy==1.4.20
> > alembic
> > tqdm>=4.62.0
> > selenium
> > selenium-wire==2.1.2
> > user_agent
> > aiohttp
> > aiohttp_socks

I'm having the same issue and my requirements look just like that

**Comment by americanseeder1865** [comment]
Alright, are you on the latest update?

**Comment by americanseeder1865** [comment]
I am going to help you all of the way through here.

**Comment by chibi624** [comment]
> 
> 
> Alright, are you on the latest update?

Yes I am

**Comment by JWeavis** [comment]
Also tested with 7.4.1.  I think it's related to recovering from the previous run as installing it to a new dir with no saved data works.
Clean install and config to folder OF_471 auths and works.
Copying the .sites from the non-working 7.4 folder to the new 741 folder causes it to error out again.

**Comment by chibi624** [comment]
I've tried a fresh download 3 or 4 times, I've never migrated any files including the .sites file. I think I have an old .sites file somewhere with content from an old account, but there's no way it's getting pathed to. Is there something more significant of a reset/uninstall besides deleting the master folder and starting from scratch? Because that's what I've been doing.

**Comment by metalmau5** [comment]
> 
> 
> Also tested with 7.4.1. I think it's related to recovering from the previous run as installing it to a new dir with no saved data works.
> Clean install and config to folder OF_471 auths and works.
> Copying the .sites from the non-working 7.4 folder to the new 741 folder causes it to error out again.
> 
> Was able to narrow it down to metadata files in one of the member folders. Moving other folders over and running the scan one person at a time. I had to delete a second set of Metadata folders from a second and third person.

This worked. Thanks.

**Comment by Gamma-Velorum** [comment]
There's got to be a better solution than deleting metadata. I have nearly 1000 folders. That'll be impossible to narrow it down.

**Comment by fatchai1994** [comment]
same issue fixed by running
> pip install -r requirements.txt

again with the master branch files replaced in old ver folder

**Comment by metalmau5** [comment]
> There's got to be a better solution than deleting metadata. I have nearly 1000 folders. That'll be impossible to narrow it down.

It's obviously not ideal, but you could just keep previously scraped content in a separate folder from the scraper.

**Comment by chibi624** [comment]
Still having this issue, nothing to do with metadata as it happens on an absolutely fresh master file. All past scrapes from old versions/before this version crapped out are on a different place on the drive.

**Comment by bmfss** [comment]
same issue, tried -master and -7.4.1 fresh install on windows 10 Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32

**Comment by bmfss** [comment]
mine happens earlier on actually but sale error;

PS C:\OnlyFans-master> python.exe start_ofd.py
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Welcome Xxxxxx | xxxxxxx
Traceback (most recent call last):
  File "C:\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\OnlyFans-master\datascraper\main_datascraper.py", line 66, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\OnlyFans-master\modules\onlyfans.py", line 101, in account_setup
    mass_messages = await authed.get_mass_messages(resume=imported)
  File "C:\OnlyFans-master\apis\onlyfans\classes\create_auth.py", line 420, in get_mass_messages
    items.extend(results2)
TypeError: 'coroutine' object is not iterable

**Comment by bmfss** [comment]
account1 has the issue (creator account, 2FA on, has a "linked account" (anther creator account), not subscribed to any creators)

account2 works! (subscriber account, 2FA off, subscribed to a few creators)

will try more combinations to attempt to narrow it down.

**Comment by apogorzelska** [comment]
I get an identical error message. The account is a creator account without subscriptions (I was helping out a friend and trying to backup her content for her).

**Comment by americanseeder1865** [comment]
There is a fix but the author has lost access to their original account for now. [Reinstall using this repo](https://github.com/DIGITALCRIMINALS/OnlyFans) and report back here.

**Comment by JWeavis** [comment]
> There is a fix but the author has lost access to their original account for now. [Reinstall using this repo](https://github.com/DIGITALCRIMINALS/OnlyFans) and report back here.

Nope.  Fresh install fails:
Scrape Processing
Name: xxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "D:\OnlyFans-7.4.2\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\OnlyFans-7.4.2\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OnlyFans-7.4.2\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "D:\OnlyFans-7.4.2\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "D:\OnlyFans-7.4.2\modules\onlyfans.py", line 144, in start_datascraper
    api_array = format_options(api_array, "apis")
  File "D:\OnlyFans-7.4.2\modules\onlyfans.py", line 1363, in format_options
    string += seperator
NameError: name 'seperator' is not defined

**Comment by americanseeder1865** [comment]
Lol I submitted a pull request from this. Unfortunatley we are going to have to install yet again. Reinstall from [my request](https://github.com/americanseeder1865/OnlyFans/tree/typo-fix) instead for now. Sorry to keep you running around in a loop.

**Comment by americanseeder1865** [comment]
You are going to have to reinstall at some point. Email me when you want to and I will help you.

**Comment by JWeavis** [comment]
> Lol I submitted a pull request for this. Unfortunately we are going to have to install yet again. Reinstall from [my request](https://github.com/americanseeder1865/OnlyFans/tree/typo-fix) instead for now. Sorry to keep you running around in a loop.

That build works.  TY

**Comment by ashaller2017** [comment]
> 

hey im grabbing this exact same error and was wondering if you found a fix

**Comment by ashaller2017** [comment]
```/onlyFansBot/OnlyFans/apis/onlyfans/classes/auth_model.py", line 448, in get_mass_messages
    items.extend(results2)
TypeError: 'coroutine' object is not iterable
sys:1: RuntimeWarning: coroutine 'create_auth.get_mass_messages' was never awaited
```
