### ISSUE TITLE
KeyError: 'author'

### ISSUE THREAD

**Issue by SomeBasicUser** [DIGITALCRIMINAL/UltimaScraper#1619]
![image](https://user-images.githubusercontent.com/55597307/130504990-8dae199d-88ba-47a6-8e3a-be274ead80f4.png)

**Comment by SH-Esteb** [comment]
mybad:

Change line 395 of apis/api_helper.py to:
media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]

**Comment by bigbluedeer** [comment]
possible duplicate of #1419

**Comment by howdothiswork** [comment]
> 
> 
> mybad:
> 
> Change line 395 of apis/api_helper.py to:
> media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]

this does not work for me :/

**Comment by americanseeder1865** [comment]
The author does know about this, but has lost access to his main account. You version is pretty old. Let's go ahead and install from [this branch](https://github.com/DIGITALCRIMINALS/OnlyFans) for now. Reinstall and report back.

**Comment by Reveren** [comment]
> mybad:
> 
> Change line 395 of apis/api_helper.py to:
> media_set = [x for x in list(chain(*media_set)) if not x.get('isReportedByMe')]

This worked for me (I was having trouble on a Free account).
