### ISSUE TITLE
Can't find .profiles/default/auth.json

### ISSUE THREAD

**Issue by cryptopunkg** [DIGITALCRIMINAL/UltimaScraper#1624]
I choose run the app locally with Mac OS,and I already use the command+shift+dot to show all the hidden files,but still can not find the folder which named as .profiles. Is there any step goes wrong? Thank you

**Comment by americanseeder1865** [comment]
Did you run the scrapper first? It will generate that directory. Then back out of it.

**Comment by PolishPatron** [comment]
these dont open for me, i click them and they pop up and then close immediately, no directories created

**Comment by eternitycomplex** [comment]
> these dont open for me, i click them and they pop up and then close immediately, no directories created

Same here. Running start_ofd.py just closes the window.
