### ISSUE TITLE
Site: 0 = onlyfans |   What does this mean?

### ISSUE THREAD

**Issue by alfredlee1204** [DIGITALCRIMINAL/UltimaScraper#1639]
Site: 0 = onlyfans |   

What does this mean?
When I enter 0 and press Enter,this will be exported

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /DATAHOARDERS/dynamic-rules/main/onlyfans.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ABB808CB20>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by LunarPenguin** [comment]
The script cant connect to github to load the dynamic rules, i suggest you try again

**Comment by Darius040** [comment]
i have same problem when i open star_ofy only say this Site: 0 = onlyfans |

**Comment by p99t37** [comment]
What would it mean that it simply "can't connect to github," is that an issue on my end? A network issue?

**Comment by LunarPenguin** [comment]
> What would it mean that it simply "can't connect to github," is that an issue on my end? A network issue?

It's need to make a request to retrieve the dynamic rules and because something was wrong with the network / internet it could not do so and gives you the error in the OP
