### ISSUE TITLE
Is it possible to only download videos longer than a certain length?

### ISSUE THREAD

**Issue by danj2k** [DIGITALCRIMINAL/UltimaScraper#1649]
Sorry if this was already asked/answered, I did a search but couldn't find any relevant threads.

Is there a way to specify the minimum length of videos that will be downloaded?

For example to avoid downloading trailers/teaser videos, a minimum length setting of say 60 or 120 seconds?

**Comment by LunarPenguin** [comment]
As far is i know this is not possible currently
