### ISSUE TITLE
Python was not found

### ISSUE THREAD

**Issue by xtephenz** [DIGITALCRIMINAL/UltimaScraper#1654]
When I try to type this inside the cmd, I got this error:
C:\Users\DELL>python start_ofd.py
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by DeepSeaOne** [comment]
Assuming you have installed Python, hit the Windows key and look for 'Manager App Execution Aliases'. Once there, DISABLE any option for python.exe or python3.exe.

You can download python [here](https://www.python.org/downloads/release/python-396/)

**Comment by xtephenz** [comment]
I have disabled it, but it still give the same error.
![image](https://user-images.githubusercontent.com/85002592/131242562-5ffade85-360a-4e6b-9003-18f52b1e8f89.png)

**Comment by sebastiendecraene** [comment]
Try `python3` instead of `python`

**Comment by Gamma-Velorum** [comment]
Did you check the box to add the python path to your Windows environment variables when installing python?

![python path](https://phoenixnap.com/kb/wp-content/uploads/2021/04/python-setup.png)

Otherwise you can't run python from any directory but only the directory you've installed it to.

**Comment by PolishPatron** [comment]
im sorry im new to all this but i have done those steps but i get the "sqlAlchemy doesnt exist

**Comment by PolishPatron** [comment]
i am able to edit with Idle but it says to double click it which i do but it brings up there error

**Comment by sharuhabeel-shareef** [comment]
try " py -m pip install SQLAlchemy"
