### ISSUE TITLE
won't download some content for a sub

### ISSUE THREAD

**Issue by J4k-The-Reaper** [DIGITALCRIMINAL/UltimaScraper#1655]
only happens with 1 sub so far. all the other ones download great. don't know what issue could be. there isnt much content to download anyway. less than a gig. any help is appreciated. wonder where DC is or if this scraper is still being supported.......

![Screenshot 2021-08-30 154959](https://user-images.githubusercontent.com/35021417/131416220-ac6e23e1-2ffe-4ed2-a356-dfbc1d3cdc9c.png)

**Comment by J4k-The-Reaper** [comment]
i see what the issue could be....she changed her onlyfans name from insideofheaven to step.sisters.gone.wild

how do i fix it so i can download?

**Comment by LunarPenguin** [comment]
DC does not have access to their account at the moment. for the time being they can be found here @DIGITALCRIMINALS

**Comment by J4k-The-Reaper** [comment]
Oh I did not know about the other account. Guess I should switch over to the new scraper....question....why did they switch or lose access to this one?

**Comment by LunarPenguin** [comment]
> why did they switch or lose access to this one?

I don't know why they switched, but they implied it is only temporary.

**Comment by kishanpatel50** [comment]
seems to be 404'ing now

**Comment by J4k-The-Reaper** [comment]
> @DIGITALCRIMINALS seems to be 404'ing now

Yeah I get same thing. So is the scraper still being supported or not? Do u switch back to old repo?

**Comment by J4k-The-Reaper** [comment]
Well......I hope the scraper gets an update soon....don't even know if it's being managed by DC anymore. Seems like they up and vanished.

**Comment by LunarPenguin** [comment]
> Seems like they up and vanished.

They forked on their temporary account and pulled in some Pull Requests. So they are still around but not as active at the moment.

**Comment by J4k-The-Reaper** [comment]
Yeah makes sense. But the page keeps 404-ing, which is why I said that.

**Comment by vfrxart** [comment]
As it stands, does 7.4.1 work? Was gonna sub to some people, but no point if I can't rip their content.

**Comment by J4k-The-Reaper** [comment]
It does and doesn't at times. But I do have the newest one that DC updated last week that works better. If you can help me share it or fork it to you then I can. I don't know anything about any of this. Lol
