### ISSUE TITLE
Memory leak in 7.4.1?

### ISSUE THREAD

**Issue by bobsage123** [DIGITALCRIMINAL/UltimaScraper#1661]
Lately for some reason, Ofscraper has been using a lot of memory, as well as CPU usage. See image below.

![image](https://user-images.githubusercontent.com/20603861/131594478-183d9612-8895-42ed-938b-4cbe18c5754c.png)

Per this quote from DIGITALCRIMINAL, I thought it was supposed to use barely any memory. So is this some kind of leak?

> Latest version of the script doesn't use any RAM. It downloads content and removes the it from the RAM.

https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1458

**Comment by foxdude42** [comment]
I'm seeing this too. Takes up to 24 GB of RAM to complete for me.
