### ISSUE TITLE
Option to Ignore File Size when checking if a file exists

### ISSUE THREAD

**Issue by nunga** [DIGITALCRIMINAL/UltimaScraper#1665]
Is it possible to have an option to ignore the File Size check when downloading, please? After I have downloaded content, I move the media file to a separate hard drive but I keep a 0 KB placeholder file in the model's folder so I know it has been previously downloaded.

Whenever I update, I have to edit **main_helper.py** and comment-out the following three lines around Line 182.

                if os.path.exists(filepath):
                  ###  if os.path.getsize(filepath) == response.content_length:
                        download_item.downloaded = True
                  ###  else:
                  ###      return download_item
                else:
                    if response_status:
                        return download_item

**Comment by DIGITALCRIMINAL** [comment]
The script already recognizes previously downloaded files if you don't move the metadata. You should store all metadata in a separate location if you're moving content.

Sent from ProtonMail mobile

-------- Original Message --------
