### ISSUE TITLE
Only Free Stuff?

### ISSUE THREAD

**Issue by SkyVolticZ** [DIGITALCRIMINAL/UltimaScraper#1678]
Hello,
can you tell me why i only can grab freestuff ?
I saw other can grab premium/paid .
Can you tell me where/how i can grab stuft im not following ?
Best Regards

**Comment by techbot2342** [comment]
No way to scrap paid content without paying for sub. Pay. Scrap

**Comment by LunarPenguin** [comment]
You can only scrape free profiles and models/content you paid to have access to.
