### ISSUE TITLE
I ran into this when I tried running, please help.

### ISSUE THREAD

**Issue by JammyTrousers** [DIGITALCRIMINAL/UltimaScraper#1682]
![image](https://user-images.githubusercontent.com/75304581/132970005-045e81d8-db8a-4284-8fc5-9fed5039b14f.png)
![Screenshot 2021-09-12 110526](https://user-images.githubusercontent.com/75304581/132970531-3509c92d-b97f-421c-bd20-5b6a6c07c729.png)
Any help will be appreciated.
I have already tried put in my email and password, which doesn't help,

**Comment by LunarPenguin** [comment]
Have you tried typing <kbd>0</kbd> en than <kbd>enter</kbd>? if not then try if that helps.

**Comment by Timmyy23** [comment]
Did you ever fit the issue if so what did you do?
