### ISSUE TITLE
Purchased/unlocked but no longer subscribed

### ISSUE THREAD

**Issue by jeff-geoff** [DIGITALCRIMINAL/UltimaScraper#1683]
Will this pull in videos/images that have been paid for if the creator is not still subscribed to?

**Comment by kavinklain** [comment]
if you paid and unsubribed within the same month, you'll still have the ability to view/scrape content until the end of the period that you paid for.

**Comment by jeff-geoff** [comment]
What I want to know is if I subscribe, unlock a video in messages and then the subscription expires, I still have access to that purchased video just not the entire profile.

How do I scrape things I’ve bought if I’m no longer subscribed to the seller?

**Comment by kavinklain** [comment]
from what i can tell, the scraper will also do through your dms with the model, as I also scraped the video previews in my dms. I'm not sure if you can still scrape dms after you can no longer view their profile. Is model in question still choosable when using the scraper?

**Comment by jeff-geoff** [comment]
The model isn’t choosable…

the videos are, however, still in the “purchased” tab on the OF homepage

**Comment by kavinklain** [comment]
oof then, im not sure if you can still scrape them then until you sub again

**Comment by jeff-geoff** [comment]
If the conversations are still in my messages, would it be possible for the script to pull them in (even if it doesn’t currently)?

Either via a white list, or maybe just a toggle that more broadly says “scrape conversations of unsubscribed models”?

I’d say I have 100+ subscriptions that have expired, but still have good content in the DMs (either PPV content, content purchased for tips, or just good free stuff, all of the above) that I would like to keep a copy of.

**Comment by galaxianloop** [comment]
i believe the scraper will grab all ppv purchased (feed & DMs) even if you aren't currently subscribed, but it can't pull non-ppv stuff from DMs with models you aren't subscribed to.

**Comment by LunarPenguin** [comment]
If you have paid for content and it shows up in your purchased tab, the scraper will still be able to download those images/videos even if you're no longer subscribed to the model

**Comment by slackett** [comment]
> If you have paid for content and it shows up in your purchased tab, the scraper will still be able to download those images/videos even if you're no longer subscribed to the model

Can you confirm how the scraper will download this content, or what needs to be done to trigger it to download this content. It does not see to download this content when I run the scraper.

**Comment by LunarPenguin** [comment]
It should be the first thing the scraper does when it starts scraping posts. you will see something like `Scraping Paid Content` on the screen and then it starts scraping the content. it if doesn't work check if `"scrape_paid_content"` in `config.json` is set to `true`

**Comment by slackett** [comment]
I do see something happen when I first run the scraper, and it does say "Scraping Paid Content", but it does not seem to save anything.

**Comment by LunarPenguin** [comment]
Could you provide me with a log of what is happening when you run the script?

**Comment by artyom2035** [comment]
Adding to the discussion.  There also maybe limits depending on the date purchased.

I renamed a paid folder, ran a scrape & it only re-downloaded a portion of the paid content that know I had.  Checked the "purchased" tab on the website, discovered it only goes back to Jan 2021.  All purchases prior to that are gone and couldn't be downloaded.  Idk, maybe OF only keeps the current calendar year's purchases under that tab.

**Comment by LunarPenguin** [comment]
i just checked and all my purchases are still visible under the `purchased` tab. in my case that goes back to June 5th 2020

**Comment by jeff-geoff** [comment]
Just to clarify—my question was about NON-purchased videos for profiles which no longer had an active subscription. E.g. videos made in exchange for tips vs. pay to unlock.

**Comment by LunarPenguin** [comment]
I think that videos made in exchange for tips are just regular videos to OnlyFans (just like any other non pay-to-view message you might get) and the only thing being different in such a case is the agreement between you and the model.

Therefore if your subscription expires so does your access to those videos. i guess there might be a way to scrape the messages of models you're no longer subscribed to but that is not possible at the moment as far as i know.

**Comment by jeff-geoff** [comment]
Any videos available to you in messages while you were subscribed remain available after your subscription ends. However, the script only scrapes purchased content and active subscriptions. The solution, I think, is to be able to manually add profiles to scrape so that the scraper crawls the old messages. I’m going to open a feature request on that.

**Comment by LunarPenguin** [comment]
> The solution, I think, is to be able to manually add profiles to scrape so that the scraper crawls the old messages. I’m going to open a feature request on that because it’s really just “scrape old conversations” not “scrape purchased/unlocked” per this issue.

I agree, i think it could be a toggle in config.conf, such as 
```json
"scrape_old_messages" : True
```
so that it does not do this by default as i dont think this is a common use case.

**Comment by jeff-geoff** [comment]
Agree that it may not be universal, but I think it is becoming more common to sell things for tips so it will become more common as that strategy gains in popularity. I’d say 30% of my subscriptions now sell content this way. Or “tip X on this message and I will send XYZ” etc…
