### ISSUE TITLE
Fastest/ easiest way to scrape when you have 100+ subs?

### ISSUE THREAD

**Issue by kavinklain** [DIGITALCRIMINAL/UltimaScraper#1685]
So at first I thought 0 would scrape them all at the same time, but it just simply goes down the list and prompts me 0 through 4 for each model and scrapes separately and then prompts again for the next model in the list. I though the 0= All in the model selection did a bulk scrape or was I wrong? if  i was any help on scraping all models, assuming I already scraped most of their content and just want to get their updates?

**Comment by DIGITALCRIMINALS** [comment]
Read the documentation
