### ISSUE TITLE
app token issue

### ISSUE THREAD

**Issue by 1jayjuan** [DIGITALCRIMINAL/UltimaScraper#1686]
![help](https://user-images.githubusercontent.com/58625932/133190612-9b94c8de-8270-4ba8-91dd-4f1320db7749.png)
cant find where to add Application token

**Comment by patsypats** [comment]
Check your Auth file

**Comment by 1jayjuan** [comment]
i dont see where to place it in the auth file

**Comment by LunarPenguin** [comment]
you can find it here: `.profiles\onlyfans\default\auth.json`
