### ISSUE TITLE
.profiles/default/auth.json is nowhere to be found.

### ISSUE THREAD

**Issue by sparker0** [DIGITALCRIMINAL/UltimaScraper#1698]
Followed the instructions. Cannot find .profiles/default/auth.json on my Windows box. 
Halp.

**Comment by fr337h37175** [comment]
> Followed the instructions. Cannot find .profiles/default/auth.json on my Windows box.
> Halp.

The config files will be generated when you run the script for first time by using on of the following:
`
python start_ofd.py | python3 start_ofd.py | double click start_ofd.py
`

**Comment by Pisak5** [comment]
I can't find .profile too. Does that mean I didn't install the script right? I'm new to Python and these stuff.

First, open command prompt. Then what? Should I type cd and go to folder or start off type pip install immediately.
