### ISSUE TITLE
Following all directions but all I get is "Site: 0 = onlyfans |" when I run start_ofd.py

### ISSUE THREAD

**Issue by johnryan989796** [DIGITALCRIMINAL/UltimaScraper#1712]
Pretty much the title. I've followed all of the directions for filling in the auth.json but I only ever get the response in the title. I've tried googling to see if anyone else has had this issue to see if I can resolve it myself but had no luck. Any help is really appreciated. Thank you.

**Comment by JustaPiano** [comment]
same problem here, i don't know what's wrong.

**Comment by HanatakeYurii** [comment]
Same for me, and if I press enter I get this:
`Site: 0 = onlyfans |

Traceback (most recent call last):
  File "C:\SpProgram\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\SpProgram\OnlyFans-7.4.1\start_ofd.py", line 41, in main
    site_choice = int(site_choice)
ValueError: invalid literal for int() with base 10: ''
`
Don't know if that helps (or just me doing nonsense).

**Comment by nquyenancu** [comment]
same problem here, i don't know what's wrong.

**Comment by PsychoSid** [comment]
What happens if you type "0" and press <enter> as it states to start the OF scrape ?

**Comment by HanatakeYurii** [comment]
@PsychoSid Thanks for this, working like a charm. I was just being stupid, I didn't get that the script was waiting for an input.

**Comment by johnryan989796** [comment]
> What happens if you type "0" and press enter as it states to start the OF scrape ?

yo you are a genius lol. I'm not a coder at all so this never occurred to me. Thank you very much friend.

**Comment by LunarPenguin** [comment]
@johnryan989796 please close this issue if the problem has been solved
