### ISSUE TITLE
rewrites auth.json and invalidates session

### ISSUE THREAD

**Issue by atrimony** [DIGITALCRIMINAL/UltimaScraper#1715]
I have tried for the 20th time to copy my cookies into `.profiles/default/auth.json`(which is what the readme says) and `.profiles/OnlyFans/default/auth.json` (which is what the CLI creates)

When running the CLI, the `auth.json` is overwritten. Then I see `Access denied.` fail 10 times. But I know that it is getting the session information correctly because the browser session is now invalid—if I try to click around on the tab where i got the cookies, it now is logged out.

So to reproduce:

1. Login to onlyfans.com
2. take `Cookie` value from `init` request
3. paste value in `.profiles/OnlyFans/default/auth.json` under `auth.cookie`
4. run `python3 start_ofd.py`
5. choose site
6. _.profiles/OnlyFans/default/auth.json is now rewritten_
7. _ten attempts with access denied_
8. Return to browser and refresh onlyfans.com
9. _logged out_

Ideas?

**Comment by jimcrapo** [comment]
check this cookie helper out - https://github.com/M-rcus/OnlyFans-Cookie-Helper

login to onlyfans, hit the icon for the extension, copy & paste into auth.json.

**Comment by colinschwegmann** [comment]
@jimcrapo how does this suggestion prevent it overwriting the auth.json?

**Comment by Xirious** [comment]
@jimcrapo how does this fix the problem with auth.json being overwritten?

**Comment by jimcrapo** [comment]
it doesn't get overwritten; it gets modified by the script to fit the format it is looking for - e.g putting the auth_id, sess, auth_hash, etc into one line "cookie".

I've watched this happen live with auth.json open in notepad++ every time I need to update due to an expired session, and never have had any auth issues.

**Comment by LunarPenguin** [comment]
@atrimony 
Could you provide us with an example of what you paste into the `auth.json` file. (of course redact you credentials first)
