### ISSUE TITLE
Hutt.co scraper

### ISSUE THREAD

**Issue by anon767346** [DIGITALCRIMINAL/UltimaScraper#1726]
Hi, I managed to find how to download images from hutt.co with a simple script.
I still am struggling to find a way to download the videos though.

To scrape a profile I'm using `https://hutt.co/hutts/ajax-posts?page={page_id}&view=view&id={profile_id}`
the images are in the format: `"\\\/images\\\/[A-Za-z0-9\-]+\\\/big\"`. just add .jpg and save to file
the videos are in the format: `"\/video\/[A-Za-z0-9\-]+\/playlist.m3u8\"`

When downloading the `*.ts` segments from the video playlist i'm getting a "error: token already used"

Are you interested in collaborating to add hutt.co to your project?

**Comment by bogdanstoian1988** [comment]
Hi, this script for hutt requeires a subscription? Thanks.

**Comment by bogdanstoian1988** [comment]
Ok thanks. I have a sub to a content creator and I know how to download their videos, it's not a public method and don't want to get patched. If you are really serious and @DIGITALCRIMINALS contact me, I'll tell them how to do it.

**Comment by anon767346** [comment]
how can i email you for the video method? it's hard it's gonna get patched, videos are eventually downloaded in some way or another in the browser

**Comment by Ficter** [comment]
Hello, newbie here. How does this work? What platform does this script work? Thanks in advance for any help!

**Comment by Usernameisnotworking** [comment]
> The script requires you to be subscribed to a content creator on hutt.co If you mean a subscription to some third party service, no of course.
> 
> But as of right now it's missing pieces and needs a lot of setting up, it's not ready to ship. I'm waiting for @DIGITALCRIMINALS to integrate it into their tool.

can you please provide your email or any other way for contact, I need that script.

**Comment by Usernameisnotworking** [comment]
> how can i email you for the video method? it's hard it's gonna get patched, videos are eventually downloaded in some way or another in the browser

can you please provide your email or any other way for contact, I need that script.
