### ISSUE TITLE
hCaptcha

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/UltimaScraper#1729]
This may or may not be related to the scraper, but has anyone gotten an hCaptcha request that's impossible to bypass when trying to log into their account? Says "captcha is incorrect" even though it acts as if you've solved it correctly.

**Comment by LunarPenguin** [comment]
I did not experience this when logging in but i did experience it when trying to verify my CC and it seems to be a OF issue and not a scraper issue

**Comment by zabatonni** [comment]
probably not related to scraper, but it's not OF issue either. I'm able to manually solve captcha, but when it's solved by 2captcha API, it always says "captcha wrong"

**Comment by 404b** [comment]
noCaptcha Ai has free plan 6K req/month you can use for

**hCaptcha Solving Variations**
- Image (Normal/Enterprise) Grid, Multiple Select, Click on Canvas
- Normal Token

Chrome Extension:
https://github.com/noCaptchaAi/chrome-extension


**Selenium Packages** :

https://github.com/Hammad69275/NoCaptchaSolver
https://github.com/claudiofepereira/nocaptchaai-selenium
https://raw.githubusercontent.com/the-captcha-ai/captcha-solver/main/usage_examples/example-selenium.py

Software Library: https://nocaptchaai.com/software

`npm install nocaptchasolver`

```
const {HCaptchaSolver} = require("nocaptchasolver")

const config = {
    apiKey,
    userAgent,
    siteKey,
    siteURL,
    enableLogger,
    loggerFunction,
    delay // in milliseconds (default is 7000ms)
}

const Solver = new HCaptchaSolver(config)


```

**Comment by LunarPenguin** [comment]
Please see #1991
