### ISSUE TITLE
please mark this project dead if it is. it has been unmaintained for months.

### ISSUE THREAD

**Issue by alectprasad** [DIGITALCRIMINAL/UltimaScraper#1732]

**Comment by rssfed23** [comment]
The project isn't dead. Maintainer lost access to his GH account and you can find the latest commits at https://github.com/DIGITALCRIMINALS/OnlyFans
(digital criminalS instead of criminal)

(as of now this old build no longer works).

**Comment by bobsage123** [comment]
> The project isn't dead. Maintainer lost access to his GH account and you can find the latest commits at https://github.com/DIGITALCRIMINALS/OnlyFans (digital criminalS instead of criminal)
> 
> (as of now this old build no longer works).

This is kinda sketchy and weird. How does someone lose access to their GH account for 2 months? It's like someone took over the account and is now pointing us to their OF project. Not saying its you, but whoever is running it.

**Comment by RuneDemomn** [comment]
Why is this project abandoned and resumed on a different account?
