### ISSUE TITLE
I got banned using this ! 

### ISSUE THREAD

**Issue by FarshadGrayson** [DIGITALCRIMINAL/UltimaScraper#1748]
after two hours of usage which it failed to download by the way i got banned ! so i guess this project needs an update for now don't use it people .

**Comment by ColtraneNadler** [comment]
> I've been using this version since it was released with no issues... I scrape multiple times a day too.
> 
> That being said, I only just realized it hasn't been updated because the latest version is on another repo. The owner lost access to his main account and had to switch to a backup. It's up to v7.5.1 as of 13 days ago on that repo and it's got kind of an alpha scraper for fansly.

whats the new repo?

**Comment by TWIISTED-STUDIOS** [comment]
> Show proof you got banned

I believe I may have also been banned for this, I used it to grab some stuff then I tried to log in normally and it will not allow me to log in, just says service unavailable or the page may have been removed, but searching my page it still finds the page so I'm unsure what happened.

**Comment by DIGITALCRIMINALS** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/pull/1627

**Comment by ColtraneNadler** [comment]
> #1627

do you have discord or telegram? onlyfans pushed some new updates, having issues where everytime i connect from script it says error- and then logs me out of browser. just started happening within the last week.

**Comment by DIGITALCRIMINALS** [comment]
Use this

https://github.com/DIGITALCRIMINALS/OnlyFans
