### ISSUE TITLE
python3 error.

### ISSUE THREAD

**Issue by Osdrix** [DIGITALCRIMINAL/UltimaScraper#1768]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS E:\OnlyFans-master> python start_ofd.py
Execute the script with Python 3.9
Press enter to continue
PS E:\OnlyFans-master> python3 start_ofd.py
python3 : The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python3 start_ofd.py
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS E:\OnlyFans-master>

**Comment by Backaache** [comment]
Python is either not installed or not in PATH. Try installing/reinstalling and make sure to check the checkbox 'Add Python 3.x to PATH' in the setup.
