### ISSUE TITLE
Hello, sir, have some questions to ask

### ISSUE THREAD

**Issue by Beryl4869** [DIGITALCRIMINAL/UltimaScraper#1772]
Please look at the picture, I don't understand the problem at all, other accounts can download normally, but it seems that it is because she has too many resources and is stuck

![image](https://user-images.githubusercontent.com/95028548/143449419-1b1d226a-39a5-4759-b3e2-5cd2bcbd7d7a.png)

**Comment by djmarioka** [comment]
I'm having the same error, please, could you fix it?. Thanks.

**Comment by docholllidae** [comment]
the author lost access to his account, or this repo?
anyway, he moved his repo to and maintains it here https://github.com/DIGITALCRIMINALS/OnlyFans  (notice the S added to the end of his name)

**Comment by wobbleninja** [comment]
> the author lost access to his account, or this repo? anyway, he moved his repo to and maintains it here https://github.com/DIGITALCRIMINALS/OnlyFans (notice the S added to the end of his name)

Thanks for this because I was wondering why on releases there is no 7.6.1 version.
