### ISSUE TITLE
Why did my login stop working?

### ISSUE THREAD

**Issue by medlhed420** [DIGITALCRIMINAL/UltimaScraper#1773]
### Discussed in https://github.com/DIGITALCRIMINAL/OnlyFans/discussions/1765

<div type='discussions-op-text'>

<sup>Originally posted by **KevinxFinnerty** November 15, 2021</sup>
Everything was fine last week but now I can't get in:

![image](https://user-images.githubusercontent.com/94399793/141841654-98cfc81a-248e-4092-b9ca-25793ed82248.png)
</div>

**Comment by docholllidae** [comment]
the author lost access to his account, or this repo?
anyway, he moved his repo to and maintains it here https://github.com/DIGITALCRIMINALS/OnlyFans  (notice the S added to the end of his name)

**Comment by sintaxx** [comment]
Oddly enough I cant even subscribe to new models, I get "something went wrong"

**Comment by sintaxx** [comment]
> the author lost access to his account, or this repo? anyway, he moved his repo to and maintains it here https://github.com/DIGITALCRIMINALS/OnlyFans (notice the S added to the end of his name)

where do you see he lost access at ?
