### ISSUE TITLE
Not downloading what I ask it to

### ISSUE THREAD

**Issue by iMoto251** [DIGITALCRIMINAL/UltimaScraper#1774]
Every time I try to download a specific thing, it never goes to that. It always goes to one specific user's messages and downloads a video. For example, I can select a completely different user, try to scrape images, and profile images and it always takes me to this completely different user's messages and tries to download a video. Am I doing something wrong?

Edit: I've narrowed it down to it's scraping my purchased videos. I guess not app breaking after they all download, but very annoying.

**Comment by docholllidae** [comment]
the author lost access to his account, or this repo?
anyway, he moved his repo to and maintains it here https://github.com/DIGITALCRIMINALS/OnlyFans  (notice the S added to the end of his name)
