### ISSUE TITLE
Install Stuck With No Error 

### ISSUE THREAD

**Issue by JamConnor** [DIGITALCRIMINAL/UltimaScraper#1778]
I am using Python 3.9. I install everything in the requirements folder fine but when I try to run "python start_ofd.py" nothing happens.

![image](https://user-images.githubusercontent.com/95383409/144314721-c2213270-961b-4cba-9946-b30a35816243.png)

Any ideas why it just says nothing and exits out?

**Comment by FadingArabChristians** [comment]
I'm having the same issue as well

**Comment by badLABZ** [comment]
You probably have two versions of python installed. Checked to see if you have others installed, I've had this problem with other apps and scripts. If not I can show you how to run it from a .bat and force python 3.9
