### ISSUE TITLE
Something went wrong. [BB91C8D6]

### ISSUE THREAD

**Issue by rciptv2019** [DIGITALCRIMINAL/UltimaScraper#1780]
Until yesterday it was working perfectly, but today it gives me this error. Is it happening to someone else?

> Auth (V1) Attempt 1/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 2/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 3/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 4/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 5/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 6/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 7/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 8/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 9/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 10/10
Something went wrong. [BB91C8D6]

**Comment by jumbubly** [comment]
I got the same error just now lol...

**Comment by G2Dolphin** [comment]
Can confirm the problem, though I can't find out what had been changed in http requests for now.

**Comment by pietrovismara** [comment]
It seems to be related with the `x-bc` header. It is now required and it wasn't until today.

**Comment by G2Dolphin** [comment]
> It seems to be related with the `x-bc` header. It is now required and it wasn't until today.

Yes, I just added this header and my requests started to work again.

**Comment by DIGITALCRIMINALS** [comment]
> It seems to be related with the `x-bc` header. It is now required and it wasn't until today.

Thanks, working on it rn

**Comment by pietrovismara** [comment]
The value is dynamic and it seems to be unique per session

**Comment by sunny9t1** [comment]
as soon as it recognize my username i got sign out of my account on the browser.. pls help

**Comment by DIGITALCRIMINALS** [comment]
Fixed, make sure to fill the x-bc value in auth.json

https://github.com/DIGITALCRIMINALS/OnlyFans

**Comment by sunny9t1** [comment]
Thank you for replying.. But i did that as soon as i started getting that error above...
But now everytime it recognize my username it log me out of browser

**Comment by G2Dolphin** [comment]
I found code that generates the value in obfuscated app.js, though I can't understand it much:

`N = function() {
            var e = O["a"].getItem("bcTokenSha");
            if (e)
                return e;
            var t = 1e12;
            return e = u()("".concat(btoa((new Date).getTime()), ".").concat(btoa(Math.random() * t), ".").concat(btoa(Math.random() * t), ".").concat(btoa(window.navigator.appVersion))),
            O["a"].setItem("bcTokenSha", e),
            e`

**Comment by DIGITALCRIMINALS** [comment]
@sunny9t1 Are you using 2FA?

@G2Dolphin I recognise that, I can't wait to start going down this rabbit hole again.

**Comment by rciptv2019** [comment]
> @sunny9t1 Are you using 2FA?
> 
> @G2Dolphin I recognise that, I can't wait to start going down this rabbit hole again.

The same thing happens to me and I don't use 2FA

**Comment by DIGITALCRIMINALS** [comment]
Are you using the same IP?

**Comment by rciptv2019** [comment]
> Are you using the same IP?

Yes

**Comment by god43** [comment]
i still have the same issue with the changes made.

**Comment by sunny9t1** [comment]
I am not using 2FA @DIGITALCRIMINALS

**Comment by hawktank** [comment]
Yes I recently started having the same error as well.  I tried adding the x-bc value to auth.json but without resolution (that entry is automatically cleared from the json values on the signin attempt as well).   For the cookie value, I tried just the auth_id and sess values from the init under Chrome Dev Tools "Network" tab which has usually worked.  I also tried just entering the entire set of data for Chrome's current cookie and the app automatically updates it when signing in - but no luck there either.  The failed app sign in attempts have Onlyfans automatically sign out in my browser.

**Comment by Scraper121** [comment]
after doing the pip insatll requirement when i try to make john file, its giving me following error on this step : python start_ofd.py


c:\OnlyFans-7.6.1>python start_ofd.py
Traceback (most recent call last):
  File "c:\OnlyFans-7.6.1\start_ofd.py", line 15, in <module>
    import tests.main_test as main_test
  File "c:\OnlyFans-7.6.1\tests\main_test.py", line 58
    match string_match:
          ^
SyntaxError: invalid syntax


please help resolve this

**Comment by Scraper121** [comment]
@DIGITALCRIMINALS please provide solution

**Comment by myunprofessionalaccount** [comment]
@Scraper121 

> after doing the pip insatll requirement when i try to make john file, its giving me following error on this step : python start_ofd.py
> 
> c:\OnlyFans-7.6.1>python start_ofd.py Traceback (most recent call last): File "c:\OnlyFans-7.6.1\start_ofd.py", line 15, in import tests.main_test as main_test File "c:\OnlyFans-7.6.1\tests\main_test.py", line 58 match string_match: ^ SyntaxError: invalid syntax
> 
> please help resolve this

You do realize that he's under no obligation to help you or anyone else, he's doing this for free.

Also, this error is unrelated to this issue, look at issues and find one that matches or make a new one.

From what I can tell though, you need to install Python 3.10 and do `python3.10 -m pip install --upgrade -r requirements.txt
`

**Comment by djmarioka** [comment]
Same error now, and access denied, I think OF has changed something.. I put a message of "Access denied" today, too.

**Comment by djmarioka** [comment]
> > It seems to be related with the `x-bc` header. It is now required and it wasn't until today.
> 
> Thanks, working on it rn

OK, thanks a lot. :)

**Comment by dballs6666** [comment]
The new version already worked for me, but now something changes, every time I try to enter the network to get the cookie and the x_bc automatically sign out, I don't know why, does anyone know how to solve it? i am using chrome for windows 10

**Comment by Scraper121** [comment]
when i do the pip install command for python 3.10 , it give the following error : 


 ERROR: Command errored out with exit status 1:
     command: 'C:\Users\peroooo\AppData\Local\Programs\Python\Python310-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\peroooo\\AppData\\Local\\Temp\\2\\pip-install-pdkx22hn\\greenlet_d4f79c9d267b49388c30052ba9153beb\\setup.py'"'"'; __file__='"'"'C:\\Users\\peroooo\\AppData\\Local\\Temp\\2\\pip-install-pdkx22hn\\greenlet_d4f79c9d267b49388c30052ba9153beb\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\peroooo\AppData\Local\Temp\2\pip-record-yqxbpg8h\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\peroooo\AppData\Local\Programs\Python\Python310-32\Include\greenlet'
         cwd: C:\Users\peroooo\AppData\Local\Temp\2\pip-install-pdkx22hn\greenlet_d4f79c9d267b49388c30052ba9153beb\
    Complete output (72 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.10
    creating build\lib.win32-3.10\greenlet
    copying src\greenlet\__init__.py -> build\lib.win32-3.10\greenlet
    creating build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_contextvars.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_cpp.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_extension_interface.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_gc.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_generator.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_generator_nested.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_greenlet.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_leaks.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_stack_saved.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_throw.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_tracing.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_version.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\test_weakref.py -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\__init__.py -> build\lib.win32-3.10\greenlet\tests
    running egg_info
    writing src\greenlet.egg-info\PKG-INFO
    writing dependency_links to src\greenlet.egg-info\dependency_links.txt
    writing requirements to src\greenlet.egg-info\requires.txt
    writing top-level names to src\greenlet.egg-info\top_level.txt
    reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs\_build'
    warning: no files found matching '*.py' under directory 'appveyor'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '.coverage' found anywhere in distribution
    adding license file 'LICENSE'
    adding license file 'LICENSE.PSF'
    adding license file 'AUTHORS'
    writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
    copying src\greenlet\greenlet.c -> build\lib.win32-3.10\greenlet
    copying src\greenlet\greenlet.h -> build\lib.win32-3.10\greenlet
    copying src\greenlet\slp_platformselect.h -> build\lib.win32-3.10\greenlet
    creating build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win32-3.10\greenlet\platform
    copying src\greenlet\tests\_test_extension.c -> build\lib.win32-3.10\greenlet\tests
    copying src\greenlet\tests\_test_extension_cpp.cpp -> build\lib.win32-3.10\greenlet\tests
    running build_ext
    building 'greenlet._greenlet' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\peroooo\AppData\Local\Programs\Python\Python310-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\peroooo\\AppData\\Local\\Temp\\2\\pip-install-pdkx22hn\\greenlet_d4f79c9d267b49388c30052ba9153beb\\setup.py'"'"'; __file__='"'"'C:\\Users\\peroooo\\AppData\\Local\\Temp\\2\\pip-install-pdkx22hn\\greenlet_d4f79c9d267b49388c30052ba9153beb\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\peroooo\AppData\Local\Temp\2\pip-record-yqxbpg8h\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\peroooo\AppData\Local\Programs\Python\Python310-32\Include\greenlet' Check the logs for full command output.

**Comment by ZeEliasF** [comment]
Been having the same problem, but I downloaded the new version fix and got this:

`Traceback (most recent call last):
  File "C:\Users\zeeli\OneDrive\Porn\OnlyFans Master\start_ofd.py", line 15, in <module>
    import tests.main_test as main_test
  File "C:\Users\zeeli\OneDrive\Porn\OnlyFans Master\tests\main_test.py", line 58
    match string_match:
          ^
SyntaxError: invalid syntax`

**Comment by btkador** [comment]
> I found code that generates the value in obfuscated app.js, though I can't understand it much:
> 
> `N = function() { var e = O["a"].getItem("bcTokenSha"); if (e) return e; var t = 1e12; return e = u()("".concat(btoa((new Date).getTime()), ".").concat(btoa(Math.random() * t), ".").concat(btoa(Math.random() * t), ".").concat(btoa(window.navigator.appVersion))), O["a"].setItem("bcTokenSha", e), e`

happy to pay if somebody can decrypt/reproduce that u() function, so we can generate x-bc automatically

**Comment by Kasdy** [comment]
> happy to pay if somebody can decrypt/reproduce that u() function, so we can generate x-bc automatically

u() function is just sha1 in hex format

**Comment by SirPenetrat0r** [comment]
@ZeEliasF 
I got the same error and I had to install Python 3.10 through the Microsoft Store (local) 
Then I was able to run the python3.10 command again without error. 

If you want you can ready my big ass post here: 
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1783

I documented my "journey" until I got it working again lol

**Comment by purpleemoji** [comment]
I knew something had changed even before I tried to scrape this morning. Yesterday, every time I clicked a model's page on my feed, OF would log me out.

**Comment by btkador** [comment]
> > happy to pay if somebody can decrypt/reproduce that u() function, so we can generate x-bc automatically
> 
> u() function is just sha1 in hex format

thanks mate.. just tried it and you're right.. it's super easy to create x-bc then.

it basically just uses the current unixtimestamp (nano), two random numbers (which can be fix in code) and window.navigator.appVersion (which is the user-agent split by first / and second half).

I can't code in python but @DIGITALCRIMINALS should be able to implement that easily.

In Golang it was basically one line of code - or 3 if you want it pretty ;-)

**Comment by blairg23** [comment]
After adding the `x-bc` header, don't forget to re-authenticate in the browser and re-add the `sess` cookie back to the `auth.json` too!

**Comment by blairg23** [comment]
> when i do the pip install command for python 3.10 , it give the following error :
> 
> ERROR: Command errored out with exit status 1: command: 'C:\Users\peroooo\AppData\Local\Programs\Python\Python310-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\peroooo\AppData\Local\Temp\2\pip-install-pdkx22hn\greenlet_d4f79c9d267b49388c30052ba9153beb\setup.py'"'"'; **file**='"'"'C:\Users\peroooo\AppData\Local\Temp\2\pip-install-pdkx22hn\greenlet_d4f79c9d267b49388c30052ba9153beb\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\peroooo\AppData\Local\Temp\2\pip-record-yqxbpg8h\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\peroooo\AppData\Local\Programs\Python\Python310-32\Include\greenlet' cwd: C:\Users\peroooo\AppData\Local\Temp\2\pip-install-pdkx22hn\greenlet_d4f79c9d267b49388c30052ba9153beb Complete output (72 lines): running install running build running build_py creating build creating build\lib.win32-3.10 creating build\lib.win32-3.10\greenlet copying src\greenlet__init__.py -> build\lib.win32-3.10\greenlet creating build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_contextvars.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_cpp.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_extension_interface.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_gc.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_generator.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_generator_nested.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_greenlet.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_leaks.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_stack_saved.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_throw.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_tracing.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_version.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests\test_weakref.py -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests__init__.py -> build\lib.win32-3.10\greenlet\tests running egg_info writing src\greenlet.egg-info\PKG-INFO writing dependency_links to src\greenlet.egg-info\dependency_links.txt writing requirements to src\greenlet.egg-info\requires.txt writing top-level names to src\greenlet.egg-info\top_level.txt reading manifest file 'src\greenlet.egg-info\SOURCES.txt' reading manifest template 'MANIFEST.in' no previously-included directories found matching 'docs_build' warning: no files found matching '_.py' under directory 'appveyor' warning: no previously-included files matching '_.pyc' found anywhere in distribution warning: no previously-included files matching '_.pyd' found anywhere in distribution warning: no previously-included files matching '_.so' found anywhere in distribution warning: no previously-included files matching '.coverage' found anywhere in distribution adding license file 'LICENSE' adding license file 'LICENSE.PSF' adding license file 'AUTHORS' writing manifest file 'src\greenlet.egg-info\SOURCES.txt' copying src\greenlet\greenlet.c -> build\lib.win32-3.10\greenlet copying src\greenlet\greenlet.h -> build\lib.win32-3.10\greenlet copying src\greenlet\slp_platformselect.h -> build\lib.win32-3.10\greenlet creating build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win32-3.10\greenlet\platform copying src\greenlet\tests_test_extension.c -> build\lib.win32-3.10\greenlet\tests copying src\greenlet\tests_test_extension_cpp.cpp -> build\lib.win32-3.10\greenlet\tests running build_ext building 'greenlet._greenlet' extension error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ ---------------------------------------- ERROR: Command errored out with exit status 1: 'C:\Users\peroooo\AppData\Local\Programs\Python\Python310-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\peroooo\AppData\Local\Temp\2\pip-install-pdkx22hn\greenlet_d4f79c9d267b49388c30052ba9153beb\setup.py'"'"'; **file**='"'"'C:\Users\peroooo\AppData\Local\Temp\2\pip-install-pdkx22hn\greenlet_d4f79c9d267b49388c30052ba9153beb\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\peroooo\AppData\Local\Temp\2\pip-record-yqxbpg8h\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\peroooo\AppData\Local\Programs\Python\Python310-32\Include\greenlet' Check the logs for full command output.

This is a problem I found with Python 3.10 and Windows 10. I haven't found a workaround, even if you download the C++ Build Tools as it mentions. See my issue here for more details: https://github.com/DIGITALCRIMINALS/OnlyFans/issues/79

**Comment by SirPenetrat0r** [comment]
@blairg23 

Hmm that's weird, I had both errors you've just mentioned - C++ one and the geckodriver one. But in the end I installed the MSVC 14 C++ packages, placed the extracted geckodriver folder in the OFLogin directory and it's working now for me. 

I'm on Win11 though.

**Comment by blairg23** [comment]
@SirPenetrat0r Interesting. I've only had this issue with Python 3.10, where those solutions didn't fix the issue in Windows 10. I did also get that Geckodriver error as a false positive when it was actually the `x-bc` header missin gor `sess` cookie variable needing to be updated.

**Comment by SirPenetrat0r** [comment]
@blairg23 
You are using the latest version though right, with the x_bc entry? 
https://github.com/DIGITALCRIMINALS/OnlyFans/releases

I just checked and with the latest release I don't even have the geckodriver folder.

**Comment by blairg23** [comment]
@SirPenetrat0r Yeah I think the Geckodriver error was just an artifact of old code or something. Once I fixed the header and `sess` cookie, it worked fine, no Geckodriver required (it should be installed via `selenium` regardless).

**Comment by bollerdominik** [comment]
> 
> thanks mate.. just tried it and you're right.. it's super easy to create x-bc then.
> 
> it basically just uses the current unixtimestamp (nano), two random numbers (which can be fix in code) and window.navigator.appVersion (which is the user-agent split by first / and second half).
> 
> I can't code in python but @DIGITALCRIMINALS should be able to implement that easily.
> 
> In Golang it was basically one line of code - or 3 if you want it pretty ;-)

Are you able to generate the x-bc header yourself?

I tried following (pseudocode):

```
getShaInHex(
    btoa(nanoTime()) + btoa(Math.random())) + btoa(Math.random()) + btoa("5.0 (Windows)")
)
```

This does not work for me

**Comment by j-ktz** [comment]
Has anyone been able to get the scraper to work since the OF update?

**Comment by blairg23** [comment]
> Has anyone been able to get the scraper to work since the OF update?

How long ago? I did this afternoon.

**Comment by SirPenetrat0r** [comment]
I just tried again yesterday before going to sleep, maybe it was today already, and it didn't work anymore. Auth Error. 
Hadn't had time to check everything but I think they've already changed something, it seems like. Gonna check again today evening

**Comment by fknMega** [comment]
Guys did you find a fix yet?

**Comment by paul123999** [comment]
Something went wrong. [BB91C8D6]  I'm in the same situation. onlyfans account sign out.

**Comment by paul123999** [comment]
Onlyfans security update.Bulk Image Downloader.
does not log in.

**Comment by paul123999** [comment]
When chrome checks the site, it logs out.

**Comment by blairg23** [comment]
I'm having no problems. I haven't updated my GH repo since I saw you guys having problems. I'm at GIT SHA `9f15b04` using the same `x-bc` and `sess` I've been using since I first mentioned it working on my Linux Ubuntu machine.

**Comment by Brandin** [comment]
Updated to the latest version, reinstalled the requirements via `pip`, but still getting the `BB91C8D6` error. When the `auth` file is first generated, there is no `x-bc`, so it seems, even though I add it, it doesn't get used which invalidates the session.

**Comment by SirPenetrat0r** [comment]
@Brandin 
Try this release here: 
https://github.com/DIGITALCRIMINALS/OnlyFans/releases

it's the latest one with the x_bc header

**Comment by fightcancer2** [comment]
How do I get the x-bc value for auth.json please?

**Comment by SirPenetrat0r** [comment]
@fightcancer2 
Open the Dev Tool when you're on Onlyfans. Search for "api" in the search bar, reload Onlyfans click on "init" and in the default tab, called "Header", scroll to the bottom, there you'll find the "x-bc" value

**Comment by Oniros** [comment]
> @fightcancer2 Open the Dev Tool when you're on Onlyfans. Search for "api" in the search bar, reload Onlyfans click on "init" and in the default tab, called "Header", scroll to the bottom, there you'll find the "x-bc" value

Thank you! Despite being able to find the x-bc and updating the sess value every time, I still get "access denied". I downloaded geckodriver but it also does nothing.

**Comment by SirPenetrat0r** [comment]
> > @fightcancer2 Open the Dev Tool when you're on Onlyfans. Search for "api" in the search bar, reload Onlyfans click on "init" and in the default tab, called "Header", scroll to the bottom, there you'll find the "x-bc" value
> 
> Thank you! Despite being able to find the x-bc and updating the sess value every time, I still get "access denied". I downloaded geckodriver but it also does nothing.

Do you have 2FA set up for your Account? Try disabling it  in your account settings and try again.

Try checking/following this "manual": 
https://pdfhost.io/v/PXwOAw3Tp_Download_the_OnlyFans_Scraper

I just slapped it together, so don't mind the formatting lol

**Comment by Touexe** [comment]
@btkador hi can you provide your golang code that generate x-bc please?

**Comment by btkador** [comment]
@Touexe 
> hi can you provide your golang code that generate x-bc please?

```
// Btoa creates a Base64-encoded ASCII string (copy of javascript function)
func Btoa(str string) (b64 string) {
	return base64.StdEncoding.EncodeToString([]byte(str))
}

// Sha1sum returns hex string from input string
func Sha1sum(str string) (sumHex string) {
	h := sha1.New()
	h.Write([]byte(str))
	return fmt.Sprintf("%x", h.Sum(nil))
}

...

// split user-agent into two after first '/'
splitAgent := strings.SplitN(Header.Get("user-agent"), "/", 2)

// create x-bc
bcToken := fmt.Sprintf("%s.%s.%s.%s",
	Btoa(fmt.Sprintf("%d", time.Now().UnixNano())),   // (new Date).getTime()
	Btoa(fmt.Sprintf("%f", 0.6445491196817532*1e12)), // Math.random() * t
	Btoa(fmt.Sprintf("%f", 0.5196423550807745*1e12)), // Math.random() * t
	Btoa(splitAgent[1]),   // 2nd half of user-agent 
)

Header.Set("x-bc", Sha1sum(bcToken))
```

**Comment by jpc23** [comment]
im not sure if this helps.

i have noticed the auth.json gets updated potentially incorrectly after this occurs. 
after you manually import the auth_id=XXXXXXXX and auth_uniq=XXXXXXXX and auth_uid=XXXXXXXX and attempt to login, the values are altered,

 they then read auth_id=XXXXXXXX; auth_uniqXXXXXXXX=; auth_uidXXXXXXXX=;

note they shift to the other side of the = sign.

**Comment by Touexe** [comment]
@btkador thanks! i followed your code. But in my case it doesn't work, all I need is just to fetch the onlyfans users basic information in json without authentication, just like you view the profile without authentication on browser. So generated x-bc token doesn't seem to work. Still get "Please refresh the page" error with status 400. Maybe it needs cookies in the header this time?

**Comment by DIGITALCRIMINALS** [comment]
The x-bc is random and set when logging in, it can't be set after your auth has been created.

**Comment by Touexe** [comment]
Solved! I wasn't able to fetch the data before without x-bc, now this self generated x-bc helped.

```
import hashlib
import random
import time
import base64

def To_base64(msg)-> str:
    msg = f"{msg}"
    msg_bytes = msg.encode("utf-8")
    base64_msg = base64.b64encode(msg_bytes)
    return base64_msg.decode("utf-8")
    
    
def generateXBC():
    useragent = '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36'
    splitedagent = useragent.split("/", 1)
    t = 1e12
    current_ns = time.time_ns()
    a = [current_ns,
        random.uniform(0, 1) * t,
        random.uniform(0, 1) * t,
        splitedagent[1],
        ]
    msg = ".".join(list(map(To_base64, a)))
    message = msg.encode("utf-8")
    hash_object = hashlib.sha1(message)
    xbc = hash_object.hexdigest()
    return xbc

````

**Comment by DIGITALCRIMINALS** [comment]
But how lol, what goes into msg? Anything?

**Comment by mhbosch** [comment]
Hey, 
can someone help me?

I have the same problem (it is the same, i become the errorcode).
My Browser session will be logged out.
So i have updated to the newest version (very many things, changed fom python 3.9 to 3.10, install visual c++).

BUT, i become the same error. Must i change some code?  I use the 7.6.1

Be heathly,

mhbosch

**Comment by NeXuS254** [comment]
I don't have the x-bc "prefilled" in my auth.json. I'm using 7.6.1. When I try to add it, it gets delete as soon as I start start_ofd.py. Can somebody pls show me how the auth.json has to look like with the x-bc header in it?

**Comment by aloysiusantioch** [comment]
> Solved! I wasn't able to fetch the data before without x-bc, now this self generated x-bc helped.
>

Awesome! How would one, in theory, apply this? Im not a python dev by any means. Know a little bash, but this is a show stopper for me :-(

**Comment by Playerhater01** [comment]
> @fightcancer2 Open the Dev Tool when you're on Onlyfans. Search for "api" in the search bar, reload Onlyfans click on "init" and in the default tab, called "Header", scroll to the bottom, there you'll find the "x-bc" value

im still unable to find the"x-bc" value. please help!

**Comment by Playerhater01** [comment]
> > > @fightcancer2 Open the Dev Tool when you're on Onlyfans. Search for "api" in the search bar, reload Onlyfans click on "init" and in the default tab, called "Header", scroll to the bottom, there you'll find the "x-bc" value
> > 
> > 
> > im still unable to find the"x-bc" value. please help!
> 
> Please take a look at the following screenshot: [imgur](https://imgur.com/a/5eca0fG)

perfect! i had to try a couple of times before it showed up
