### ISSUE TITLE
get this error update my Python to 3.10 that OnlyFans DataScraper v7.6.1 need

### ISSUE THREAD

**Issue by Fall0n** [DIGITALCRIMINAL/UltimaScraper#1783]
C:\Temp\OnlyFans DataScraper v7.6.1>start_ofd.py
Execute the script with Python 3.10
Press enter to continue

C:\Temp\OnlyFans DataScraper v7.6.1>start_ofd.py
Traceback (most recent call last):
  File "C:\Temp\OnlyFans DataScraper v7.6.1\start_ofd.py", line 7, in <module>
    from rich import panel
ModuleNotFoundError: No module named 'rich'

C:\Temp\OnlyFans DataScraper v7.6.1>pip3 install -r requirements.txt
Fatal error in launcher: Unable to create process using '"C:\Users\hupa\AppData\Local\Programs\Python\Python39\python.exe"  "C:\Users\hupa\AppData\Local\Programs\Python\Python39\Scripts\pip3.exe" install -r requirements.txt': The system cannot find the file specified.

**Comment by SirPenetrat0r** [comment]
Try updating the packages with: 
`python3.10 -m pip install --upgrade -r requirements.txt`

I get the same error - but I can't use "python3.10" when I try to run above mentioned command in the D:\OnlyFans-7.6.1 directory it outputs the following: 
```
'python3.10' is not recognized as an internal or external command,
operable program or batch file.

D:\OnlyFans-7.6.1>
```

**Comment by Scraper121** [comment]
when i do the pip install command for python 3.10 , it give the following error , please help sir

ERROR: Command errored out with exit status 1:
command: 'C:\Users\peroooo\AppData\Local\Programs\Python\Python310-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\peroooo\AppData\Local\Temp\2\pip-install-pdkx22hn\greenlet_d4f79c9d267b49388c30052ba9153beb\setup.py'"'"'; file='"'"'C:\Users\peroooo\AppData\Local\Temp\2\pip-install-pdkx22hn\greenlet_d4f79c9d267b49388c30052ba9153beb\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\peroooo\AppData\Local\Temp\2\pip-record-yqxbpg8h\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\peroooo\AppData\Local\Programs\Python\Python310-32\Include\greenlet'
cwd: C:\Users\peroooo\AppData\Local\Temp\2\pip-install-pdkx22hn\greenlet_d4f79c9d267b49388c30052ba9153beb
Complete output (72 lines):
running install
running build
running build_py
creating build
creating build\lib.win32-3.10
creating build\lib.win32-3.10\greenlet
copying src\greenlet_init_.py -> build\lib.win32-3.10\greenlet
creating build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_contextvars.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_cpp.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_extension_interface.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_gc.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_generator.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_generator_nested.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_greenlet.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_leaks.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_stack_saved.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_throw.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_tracing.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_version.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests\test_weakref.py -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests_init_.py -> build\lib.win32-3.10\greenlet\tests
running egg_info
writing src\greenlet.egg-info\PKG-INFO
writing dependency_links to src\greenlet.egg-info\dependency_links.txt
writing requirements to src\greenlet.egg-info\requires.txt
writing top-level names to src\greenlet.egg-info\top_level.txt
reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs_build'
warning: no files found matching '.py' under directory 'appveyor'
warning: no previously-included files matching '.pyc' found anywhere in distribution
warning: no previously-included files matching '.pyd' found anywhere in distribution
warning: no previously-included files matching '.so' found anywhere in distribution
warning: no previously-included files matching '.coverage' found anywhere in distribution
adding license file 'LICENSE'
adding license file 'LICENSE.PSF'
adding license file 'AUTHORS'
writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
copying src\greenlet\greenlet.c -> build\lib.win32-3.10\greenlet
copying src\greenlet\greenlet.h -> build\lib.win32-3.10\greenlet
copying src\greenlet\slp_platformselect.h -> build\lib.win32-3.10\greenlet
creating build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win32-3.10\greenlet\platform
copying src\greenlet\tests_test_extension.c -> build\lib.win32-3.10\greenlet\tests
copying src\greenlet\tests_test_extension_cpp.cpp -> build\lib.win32-3.10\greenlet\tests
running build_ext
building 'greenlet._greenlet' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\peroooo\AppData\Local\Programs\Python\Python310-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\peroooo\AppData\Local\Temp\2\pip-install-pdkx22hn\greenlet_d4f79c9d267b49388c30052ba9153beb\setup.py'"'"'; file='"'"'C:\Users\peroooo\AppData\Local\Temp\2\pip-install-pdkx22hn\greenlet_d4f79c9d267b49388c30052ba9153beb\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\peroooo\AppData\Local\Temp\2\pip-record-yqxbpg8h\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\peroooo\AppData\Local\Programs\Python\Python310-32\Include\greenlet' Check the logs for full command output.

**Comment by Fall0n** [comment]
> python3.10 -m pip install --upgrade -r requirements.txt

that not helping. i get more errors and it reboot my pc..

**Comment by SirPenetrat0r** [comment]
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

Look at the end of the error message, it says why it's not working. You need to download and install Microsoft Visual C++ 14.0 - then run the pip install command again. 

@Fall0n 
What is happening then? I can't really help if I don't know what error appears. 
Where do you run the command? Do you have Python 3.10? What's the output after you run the command?

**Comment by wobbleninja** [comment]
@SirPenetrat0r So I have the same issue "ModuleNotFoundError: No module named 'aiohttp_socks'"

And I know it's because it didn't finish installing the requirements and that's because I'm missing that "Microsoft Visual C++ 14.0 or greater" and my requirements installation stops when trying to install that "psutil" thing.

The thing is, how did you exactly downloaded that C++ 14? I did download the Visual Studio Installer from the link the error provides itself but it's a mess in there. I have no idea what to download and save some gbs because no matter what I choose it tries to install some 2gb+ stuff..

I think going under "Individual components" and installing something from there?

**Comment by SirPenetrat0r** [comment]
@wobbleninja 
Here's a pic with what I have installed:
https://imgur.com/a/xxEIbbK

Just download it here: 
https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

**Comment by wobbleninja** [comment]
@SirPenetrat0r Not sure what difference does it make to have it from Microsoft Store but so far my Python seems to be working fine. Or I don't know, I wanted to go step by step until I come to that point and see if I really need to install it from there.

The thing is that this is kinda sad. You gotta download 4gb on your PC in order to make it work. It was working fine and now we need to add some random stuff on top just to make this program work and I hope there'll be a different workaround soon. Maybe some changes soon that won't require all that

**Comment by SirPenetrat0r** [comment]
> @SirPenetrat0r Not sure what difference does it make to have it from Microsoft Store but so far my Python seems to be working fine. Or I don't know, I wanted to go step by step until I come to that point and see if I really need to install it from there.
> 
> The thing is that this is kinda sad. You gotta download 4gb on your PC in order to make it work. It was working fine and now we need to add some random stuff on top just to make this program work and I hope there'll be a different workaround soon. Maybe some changes soon that won't require all that

I had Python installed via their homepage. So I had the Python 3.9 and 3.10 (64-bit) executables, but it never worked with them. And cmd always pointed me to the MS Store when trying to use python3.10 -command then I just went to MS Store, installed PYthon 3.10 and it worked lol 

Yeah, I don't really know the inner workings of Python etc. and all this programming stuff - maybe there'll be a change for it to require less space etc.

**Comment by wobbleninja** [comment]
Either way, as it seems now, in order to make it work you need the new version (for the x_bc thing) and for that to work you are forced to install some 4gb on top (VIsual C++) so you can get all the requirements for the program to work. I'm not sure if that's a Python thing or just the specific requirements for the program but it's kinda pain in the ass to know that you have to download extra 4gb.

**Comment by hawktank** [comment]
the Readme says 3.10.X Support but I found the latest 3.9.X doesn't get errors with updating the requirements packages

**Comment by hawktank** [comment]
> Either way, as it seems now, in order to make it work you need the new version (for the x_bc thing) and for that to work you are forced to install some 4gb on top (VIsual C++) so you can get all the requirements for the program to work. I'm not sure if that's a Python thing or just the specific requirements for the program but it's kinda pain in the ass to know that you have to download extra 4gb.

After that,  you got the OF login working?

**Comment by SirPenetrat0r** [comment]
@hawktank Yes, it's working. At least for me. I've used it today.

**Comment by wobbleninja** [comment]
@hawktank 
> After that, you got the login working?

Yeah. It works now. And I had to install the Visual C++ which is a useless 3.72gb taken from my disk for no other reason than the requirements to continue installing. I don't know if I still need it but I kept it there. 

I don't have the Microsoft Store python version. My 3.10 python works fine from the official Python site. 

Also, if anyone installs the Visual Studio Installer all you need to do (_at least that's what I did_) is to go on Visual Studio Community 2019 then under the Workloads > Desktop Development with C++ and click it. It will mark around 11 stuff to install. **I think you need them all** because I tried to install the Visual C++ individually but it would still give me errors. All this.. for just the requirements to install. 

Then it's all about how Python is installed correctly to your PC and it can run the program normally. For example the dude above had problems and needed to get the Microsoft Store python while I'm fine from their site.

Now obviously, we are people who have no idea about coding or Python and all that stuff. And we're talking like the amateurs we are and if anyone with knowledge will read what we write, they'll probably have epilepsy on how bad we are on those things but well, we try to help each other here.

I just only hope there will be a workaround to get rid of Visual C++ from our PC. It's just lame that you need extra 4gb installed in order to make a 2mb program to work.

**Comment by j-ktz** [comment]
I've downloaded the latest version and installed 3.10. I get this error: `ModuleNotFoundError: No module named 'psutil'`but if I run `python3.10 -m pip install --upgrade -r requirements.txt` I get this:

```
Running setup.py clean for psutil
Failed to build psutil
Installing collected packages: psutil, lxml, beautifulsoup4, alembic
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.10/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sb/jgd7y4pd4nqcr5vy0pmxpwq00000gn/T/pip-install-hbygspkf/psutil_b2305438fb3140f38798b3ba7086c133/setup.py'"'"'; __file__='"'"'/private/var/folders/sb/jgd7y4pd4nqcr5vy0pmxpwq00000gn/T/pip-install-hbygspkf/psutil_b2305438fb3140f38798b3ba7086c133/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sb/jgd7y4pd4nqcr5vy0pmxpwq00000gn/T/pip-record-1bpls8en/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10/psutil
```

**Comment by wobbleninja** [comment]
@j-ktz Yeah, I was stuck at the same psutil thing. But mine was asking to install Visual C++. And then it could install it normally

**Comment by j-ktz** [comment]
@wobbleninja Did you use a line of code to install?

**Comment by wobbleninja** [comment]
Of course. You run the `pip install --upgrade -r requirements.txt `

**Comment by j-ktz** [comment]
@wobbleninja Tried that but get the same error. :/

**Comment by wobbleninja** [comment]
Are you sure you have Visual C++ installed correctly? [Look](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1783#issuecomment-986285537) what I wrote above

**Comment by j-ktz** [comment]
@wobbleninja Yes, when I run that command, this is the output:

`Requirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.26.0)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (1.26.7)
Requirement already satisfied: win32-setctime in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.0.4)
Requirement already satisfied: python-socks[asyncio] in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (2.0.0)
Collecting psutil
  Using cached psutil-5.8.0.tar.gz (470 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (2.8.2)
Collecting lxml
  Using cached lxml-4.6.4-cp310-cp310-macosx_10_14_x86_64.whl (4.5 MB)
Requirement already satisfied: mergedeep in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (1.3.4)
Requirement already satisfied: jsonpickle in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (2.0.0)
Requirement already satisfied: ujson in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (4.3.0)
Requirement already satisfied: sqlalchemy==1.4.20 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (1.4.20)
Collecting alembic
  Using cached alembic-1.7.5-py3-none-any.whl (209 kB)
Requirement already satisfied: tqdm>=4.62.0 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (4.62.3)
Requirement already satisfied: selenium in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (4.1.0)
Requirement already satisfied: selenium-wire==2.1.2 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (2.1.2)
Requirement already satisfied: user_agent in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 17)) (0.1.10)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (3.8.1)
Requirement already satisfied: aiohttp_socks in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 19)) (0.7.1)
Requirement already satisfied: rich in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 20)) (10.15.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/site-packages (from sqlalchemy==1.4.20->-r requirements.txt (line 12)) (1.1.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests->-r requirements.txt (line 1)) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/site-packages (from requests->-r requirements.txt (line 1)) (2.0.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests->-r requirements.txt (line 1)) (2021.10.8)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/site-packages (from beautifulsoup4->-r requirements.txt (line 2)) (2.3.1)
Requirement already satisfied: async-timeout>=3.0.1 in /usr/local/lib/python3.10/site-packages (from python-socks[asyncio]->-r requirements.txt (line 5)) (4.0.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/site-packages (from python-dateutil->-r requirements.txt (line 7)) (1.16.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.10/site-packages (from alembic->-r requirements.txt (line 13)) (1.1.6)
Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.10/site-packages (from selenium->-r requirements.txt (line 15)) (0.9.2)
Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.10/site-packages (from selenium->-r requirements.txt (line 15)) (0.19.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 18)) (1.7.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 18)) (21.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 18)) (1.2.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 18)) (1.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 18)) (5.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /usr/local/lib/python3.10/site-packages (from rich->-r requirements.txt (line 20)) (2.10.0)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /usr/local/lib/python3.10/site-packages (from rich->-r requirements.txt (line 20)) (0.4.4)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /usr/local/lib/python3.10/site-packages (from rich->-r requirements.txt (line 20)) (0.9.1)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.10/site-packages (from async-timeout>=3.0.1->python-socks[asyncio]->-r requirements.txt (line 5)) (4.0.1)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.10/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 15)) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.10/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 15)) (1.1.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 15)) (1.2.0)
Requirement already satisfied: async-generator>=1.9 in /usr/local/lib/python3.10/site-packages (from trio~=0.17->selenium->-r requirements.txt (line 15)) (1.10)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.10/site-packages (from trio-websocket~=0.9->selenium->-r requirements.txt (line 15)) (1.0.0)
Requirement already satisfied: pyOpenSSL>=0.14 in /usr/local/lib/python3.10/site-packages (from urllib3->-r requirements.txt (line 3)) (21.0.0)
Requirement already satisfied: cryptography>=1.3.4 in /usr/local/lib/python3.10/site-packages (from urllib3->-r requirements.txt (line 3)) (36.0.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.10/site-packages (from Mako->alembic->-r requirements.txt (line 13)) (2.0.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/site-packages (from cryptography>=1.3.4->urllib3->-r requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.10/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium->-r requirements.txt (line 15)) (0.12.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=1.3.4->urllib3->-r requirements.txt (line 3)) (2.21)
Building wheels for collected packages: psutil
  Building wheel for psutil (setup.py) ... done
  Created wheel for psutil: filename=psutil-5.8.0-cp310-cp310-macosx_11_0_x86_64.whl size=236630 sha256=beb7176f204aa29c4e2c2911e805d67ba76de047c6003f51ce4689769b1daecc
  Stored in directory: /Users/j_k/Library/Caches/pip/wheels/12/a3/6d/615295409067d58a62a069d30d296d61d3ac132605e3a9555c
Successfully built psutil
Installing collected packages: psutil, lxml, beautifulsoup4, alembic
  WARNING: The script alembic is installed in '/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed alembic-1.7.5 beautifulsoup4-4.10.0 lxml-4.6.4 psutil-5.8.0`

**Comment by wobbleninja** [comment]
@j-ktz And what happens now if you run the program from `start_ofd.py`

Because I think I had the same problem but the psutil was installed correctly as it also shown in your case too. And the program runs normally now.
