### ISSUE TITLE
Something went wrong. [BB91C8D6]

### ISSUE THREAD

**Issue by dawforpc** [DIGITALCRIMINAL/UltimaScraper#1788]
Auth (V1) Attempt 1/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Archive Completed in 0.21 Minutes
Pausing scraper for 0 seconds.

Yesterday till day it was working pretty well but late night it started with all this !!! Finally when I solved my one problem then this !!!

**Comment by fightcancer2** [comment]
Exact same issue for me.

Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.28 Minutes
Pausing scraper for 0 seconds.

**Comment by wobbleninja** [comment]
Bump
Same here

**Comment by chelaxian** [comment]
it seems that onlyfans has fixed multilogin and access to multiple posts at same time.
i got this before logoff:
https://onlyfans.com/api2/v2/posts?limit=10&offset=0&skip_users_dups=1&format=infinite

**Comment by Jar4ek** [comment]
I have the same problem.
