### ISSUE TITLE
Problem Loading

### ISSUE THREAD

**Issue by toschimaka** [DIGITALCRIMINAL/UltimaScraper#1797]
Hello! Ive tried everything to try and get it to work (checked the cookie like 10 times) and once it gets to the browser part it doesnt even input the password/email

This is the "log":

Site: 0 = onlyfans |
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser
Opening Browser

Hope it gets fixed

**Comment by Tyemnata** [comment]
What version of the datascraper are you running? What version of python do you have?

**Comment by LP560** [comment]
> What version of the datascraper are you running? What version of python do you have?

im using the latest of everything after upgrading to them and get the same issues. Even before the upgrade. I believe its something done backend on OF because each time i try to auth like i've always done i get logged out on the website

**Comment by Tyemnata** [comment]
I had it working in October. I updated today and even trying the latest git I can't get it working. It's some combination of OF and the script that has has changed.

**Comment by LucioSaldivar** [comment]
Make sure you are using google and input cookie settings from google browser. I had this issue and it turned out it was my browser.
