### ISSUE TITLE
Error auth_json.bak

### ISSUE THREAD

**Issue by okanshine** [DIGITALCRIMINAL/UltimaScraper#1808]
Hello
I'm having a problem with your program

When i fill my info on auth_json like cookie, auth_id, user agent, etc
and then show file auth_json.bak

Screenshot :
https://prnt.sc/23fx44c

I hope you fix it

Thanks

**Comment by superfan12345** [comment]
remove those images. they have your onlyfans id in them

**Comment by okanshine** [comment]
> remove 23fx2t8. it has your onlyfans id in it.

what you mean ? i dont understand.. can you give me a scerenshot

**Comment by superfan12345** [comment]
https://prnt.sc/23fx2t8 remove this. it can get you banned from onlyfans

**Comment by okanshine** [comment]
> https://prnt.sc/23fx2t8 remove this. it can get you banned from onlyfans

ok i will delete this case and the open case again, thanks you for the information

**Comment by okanshine** [comment]
> https://prnt.sc/23fx2t8 remove this. it can get you banned from onlyfans

can you delete the comment ?

**Comment by superfan12345** [comment]
remove your quote of my comment.

**Comment by okanshine** [comment]
Yes, but you should remove revision

https://prnt.sc/23g5spw

**Comment by superfan12345** [comment]
u dont need to remover anything else. but don't show things like auth and things like that

**Comment by okanshine** [comment]
delete comment

**Comment by okanshine** [comment]
Just do it
https://prnt.sc/23g6otp

**Comment by superfan12345** [comment]
thanks i guess
