### ISSUE TITLE
Stopped working for me as of today. Anyone else see the same?

### ISSUE THREAD

**Issue by python-qwsa** [DIGITALCRIMINAL/UltimaScraper#1848]
I think my cookie config is fine as my method has been working for a while. 

All of the sudden I am getting this:

```
Auth (V1) Attempt 1/10
Access denied.

```

Anyone else?

**Comment by aizenn1** [comment]
No the auth still working, I think you just need to get a new cookie because it changed or something like that

**Comment by narbigcito** [comment]
I have same problem. :(

**Comment by aizenn1** [comment]
> I have same problem. :(

Email and Pass not required just let them empty, make sure to change the folder called default in ".profiles\OnlyFans" to your OF username, this might fix your issue

**Comment by python-qwsa** [comment]
> When I extracted the data from chrome it worked correctly.

Did you extract the data with the network trace or are you using a special chrome extension / tool?

**Comment by narbigcito** [comment]
> > When I extracted the data from chrome it worked correctly.
> 
> Did you extract the data with the network trace or are you using a special chrome extension / tool?

No, use the default chrome developer tool in the Network section and in the file named init, there were all the variables

**Comment by blade2005** [comment]
i had to use py3.10 and manually populate the x-bc header to get it to work.
