### ISSUE TITLE
Fail accessing to content nowadays

### ISSUE THREAD

**Issue by aizenn1** [DIGITALCRIMINAL/UltimaScraper#1850]
Hello there folks, I'm trying to scrape a model content with 200+ videos but I only getting 22 does anyone have the same problem nowadays? I have tried with 2 other models and the same problem not downloading the whole content just a few of it! Btw the models posting non PPV vids so the vids not locked or something, I think onlyfans changed the api or something

**Comment by aizenn1** [comment]
Check this screenshot: https://imgur.com/FY6xoE0 as you can see the process getting stopped on 25%

**Comment by diffracteD** [comment]
Hi,
Can you help me get the 'cookie' needed to proceed with the program. I cant find it in inspect>network>api like it's mentioned.
Thanks.

**Comment by BerserkRaged** [comment]
I'm receiving the same issue =/
