### ISSUE TITLE
Access denied, and logs me out of the site.

### ISSUE THREAD

**Issue by Jaboc21** [DIGITALCRIMINAL/UltimaScraper#1853]
I've used this program before and it has worked fine, but now it logs me out of the site and access is denied to the program.

**Comment by AE2071cm** [comment]
I'm having the exact same issue, I've tried with different browsers but no dice, can anyone confirm if it's still working?

**Comment by anon-ion** [comment]
I'm having the same issues. Is there anyone at all that has this working? I'm even tying with the OnlyFans-Cookie-Helper plugin. I keep getting 

    Something went wrong. [BB91C8D6]

And then it logs me out in the browser.

**Comment by shawn8888** [comment]
Same here. no longer working.

**Comment by SterlingSavariau** [comment]
It's wild how the devs won't even try to assist the problem.

**Comment by eriktux** [comment]
Anyone else noticed that the content of the cookie appears to be much different than before?
This program needs an update for sure!

I have a workaround guys!!
I found a repo on the docker hub, which contains a recent image.
Here:
[(https://hub.docker.com/r/dockanon6573456/onlyfans)]

Notice that we now have a new value to fill in:

```
    {"cookie":"cookie_value"}
    {"x-bc":"x-bc_value"}
    {"user-agent":"user-agent_value"}
```

The "x-bc" value is new!  But you'll find it the very same way you find your cookie and your user-agent.
Also the cookie is diifferent than before, but I've pasted that whole thing in the auth file, and then I'm good to go!
Actually downloading 21G of data  :D

**Comment by antithesis-b** [comment]
> Anyone else noticed that the content of the cookie appears to be much different than before? This program needs an update for sure!
> 
> I have a workaround guys!! I found a repo on the docker hub, which contains a recent image. Here: (https://hub.docker.com/r/dockanon6573456/onlyfans)
> 
> Notice that we now have a new value to fill in:
> 
> ```
>     {"cookie":"cookie_value"}
>     {"x-bc":"x-bc_value"}
>     {"user-agent":"user-agent_value"}
> ```
> 
> The "x-bc" value is new! But you'll find it the very same way you find your cookie and your user-agent. Also the cookie is diifferent than before, but I've pasted that whole thing in the auth file, and then I'm good to go! Actually downloading data from OF :D

The reason is that the Dev lost access to this account. I believe this is the current fork: https://github.com/KptnKMan/DIGITALCRIMINAL-OnlyFans

**Comment by eriktux** [comment]
> The reason is that the Dev lost access to this account. I believe this is the current fork: https://github.com/KptnKMan/DIGITALCRIMINAL-OnlyFans or this: https://github.com/DIGITALCRIMINALS/OnlyFans I'm not quite sure which is the most up-to-date

Wow, thank you so much!  I did not realize the dev restarted another repo.
Well THIS one is more up-to-date:
https://github.com/DIGITALCRIMINALS/OnlyFans

And I really thought it was the "same" page, without noticing the slight difference in name (the S!)

So he started alone:
DIGITALCRIMINAL

And now they're a group!
DIGITALCRIMINALS

The business is growing  :D
