### ISSUE TITLE
To those who's new here, the dev can't access his main account. You can visit his new repo with up to date commits and fixes

### ISSUE THREAD

**Issue by Touexe** [DIGITALCRIMINAL/UltimaScraper#1867]
here's the link : https://github.com/KptnKMan/DIGITALCRIMINAL-OnlyFans

**Comment by spoobles** [comment]
I don't know what that repo is, but the new account is https://github.com/DIGITALCRIMINALS/OnlyFans

**Comment by J4k-The-Reaper** [comment]
So which one is it now? So confused

**Comment by spoobles** [comment]
https://github.com/KptnKMan/DIGITALCRIMINAL-OnlyFans - last code update was 6 months ago

https://github.com/DIGITALCRIMINALS/OnlyFans - last code update was 4 days ago

**Comment by DIGITALCRIMINAL** [comment]
Yes, DIGITALCRIMINALS is my account :)
OP posted the wrong link.

Sent from ProtonMail mobile

-------- Original Message --------
