### ISSUE TITLE
please any one help me 

### ISSUE THREAD

**Issue by HusseinElnadi** [DIGITALCRIMINAL/UltimaScraper#1873]
Hello all
Recently the code was working perfectly and when I click on (updater) the code does not work now what do I do

ineed any help please ♥

![Untitled](https://user-images.githubusercontent.com/104869230/169406868-f971551a-7ae1-4ccb-a5e4-d72e4c74ce0b.png)

**Comment by demib72** [comment]
Not the most helpful opening of an issue. Did you open it in the command line? If you did, did an error show? If so, could you paste/screenshot it?
