### ISSUE TITLE
.profiles/default/auth.json was not created

### ISSUE THREAD

**Issue by KimchiDealer** [DIGITALCRIMINAL/UltimaScraper#1876]
I'm following the instructions to run the app locally (Windows 10). I am using python 3.10

 Steps that I've done:
1.  `pip install --upgrade --user -r requirements.txt`
2. python start_ofd.py | python3 start_ofd.py | double click start_ofd.py
 

Step 1. worked perfectly 

after doing step 2 I'm left with the script stating 'Press enter to continue', and profiles/default/auth.json is nowhere to be seen within the folder. I've also tried double click start_ofd.py but still nothing

What am I doing wrong?
Thanks in advance to anyone willing to help.
(Before)
![image](https://user-images.githubusercontent.com/106943626/172096085-1dd974ae-36c0-4fcf-9873-7e87a848096a.png)

(After)
![image](https://user-images.githubusercontent.com/106943626/172096437-3f4c9e40-b090-4474-89e8-e3c5b6153a5f.png)

**Comment by sly-liu** [comment]
same

**Comment by fightcancer2** [comment]
Try 7.6.1 instead of 7.4.1.

**Comment by madebyaman** [comment]
Same issue.
@fightcancer2 where can I find 7.6.1
