### ISSUE TITLE
我完全不知道怎么搞，有人来教我一下吗？

### ISSUE THREAD

**Issue by yujianshenming** [DIGITALCRIMINAL/UltimaScraper#1891]
我完全不知道怎么搞，有人来教我一下吗？

**Comment by LunarPenguin** [comment]
这个版本的程序已经死了。 请去[这里](https://github.com/DIGITALCRIMINALS/OnlyFans) (translated using google translate)

This version of the program is dead. please go [here](https://github.com/DIGITALCRIMINALS/OnlyFans)
