### ISSUE TITLE
AttributeError: module 'selenium.webdriver' has no attribute 'Opera'

### ISSUE THREAD

**Issue by ssuukk** [DIGITALCRIMINAL/UltimaScraper#1901]
Traceback (most recent call last):
  File "/mnt/d/Projekty/OnlyFans/start_ofd.py", line 16, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "/mnt/d/Projekty/OnlyFans/datascraper/main_datascraper.py", line 6, in <module>
    import modules.onlyfans as m_onlyfans
  File "/mnt/d/Projekty/OnlyFans/modules/onlyfans.py", line 13, in <module>
    import extras.OFLogin.start_ofl as oflogin
  File "/mnt/d/Projekty/OnlyFans/extras/OFLogin/start_ofl.py", line 2, in <module>
    from seleniumwire import webdriver
  File "/home/qus/.local/lib/python3.9/site-packages/seleniumwire/webdriver/__init__.py", line 1, in <module>
    from selenium.webdriver import *  # noqa
AttributeError: module 'selenium.webdriver' has no attribute 'Opera'

**Comment by cklapperich3** [comment]
Seems to be a version issue with Selenium-wire 
pip uninstall selenium-wire then pip install elenium-wire  fixed it for me

**Comment by peatu** [comment]
I have the same issue i hope it can be resolved soon.

**Comment by class5vapor** [comment]
Samsies...anyone know why yet?

**Comment by ashk123** [comment]
Same

**Comment by Crazylocust** [comment]
same it's a pain and only 2 days left for ripping

**Comment by wxarz** [comment]
> same it's a pain and only 2 days left for ripping

ripping what

**Comment by class5vapor** [comment]
> > same it's a pain and only 2 days left for ripping
> 
> ripping what

Farts, I guess. LoL
I think the term meant was Scraping, but yeah, I have like 25 days left if this gets cleared-up I can try to scrape an account of the media.

=]

**Comment by Crazylocust** [comment]
Yes farts maybe. Sorry ahah, you were right, I was thinking scraping. I kept reinstalling, trying on another pc, but nothing worked.

**Comment by Rowan2109** [comment]
This is the solution to the problem:
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/503

**Comment by class5vapor** [comment]
> This is the solution to the problem: [DIGITALCRIMINALS#503](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/503)

Thanks so much Rowan, so if I understand correctly it's basically downgrading the selenium in line 15 of the requirements.txt.

I edited this file, saved it, ran the update and it did say that it un-installed the newer one and successfully install the older one.
I'll try later to scrape 'n see what happens.

I'll let the thread know how she goes - might only be early tomorrow mornin' tho

=]

Thanks again though, in advance!

**Comment by class5vapor** [comment]
> Yes farts maybe. Sorry ahah, you were right, I was thinking scraping. I kept reinstalling, trying on another pc, but nothing worked. Whereas until a few days ago everything worked out fine.

All good man, glad we can have a sense of humour about it, try what Rowan suggested in this post below for the fix and you may be able to scrape in your last 2 days!! Fingers Crossed!

=]

**Comment by Rowan2109** [comment]
Its the last post by FightCancer that was the fix, also just in advance because I had this problem as well. If you get a "get" error after selecting what you want to download go to OnlyFans-7.6.1\.settings and open the .config file, then change the  "auto_api_choice": auto, to  "auto_api_choice": false,
There are 3 of those to change, 1 for each website option.

**Comment by class5vapor** [comment]
> > This is the solution to the problem: [DIGITALCRIMINALS#503](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/503)
> 
> Thanks so much Rowan, so if I understand correctly it's basically downgrading the selenium in line 15 of the requirements.txt.
> 
> I edited this file, saved it, ran the update and it did say that it un-installed the newer one and successfully install the older one. I'll try later to scrape 'n see what happens.
> 
> I'll let the thread know how she goes - might only be early tomorrow mornin' tho
> 
> =]
> 
> Thanks again though, in advance!

***SOLVED!***
Can Confirm I'm Up 'n Running As-Of This Morning By Simply Changing Line 15 in FightCancer's Fix!
