### ISSUE TITLE
TypeError:  'NoneType' object is not iterable

### ISSUE THREAD

**Issue by silversurfer7702** [DIGITALCRIMINAL/UltimaScraper#1919]
Everything was working last night, but just tried to scrape and got this:

![image](https://user-images.githubusercontent.com/111753340/186765999-9d6a24c8-f374-4d8e-9699-85d205e4a5c7.png)

Anyone else coming across this?  It logged into my account fine, and I can see all profiles to rip.  When I choose one (or all), this is the result.  Any help would be appreciated!

**Comment by tdex89** [comment]
How do you resolve the issue on a Mac?

**Comment by drobb0690** [comment]
getting it as well, was working just fine last night

**Comment by icedstick** [comment]
Also having this issue just today

**Comment by carl2585** [comment]
I get this error too

**Comment by obzach** [comment]
same problem here

**Comment by anoeks** [comment]
Yep same error for me this morning too

**Comment by johnnyturbo87** [comment]
Any fix for this?

**Comment by silversurfer7702** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/606#issuecomment-1228024483

This fix did it for me!! FYI the create_user.py file is located in apis/onlyfans/classes

I think most of you should be able to find a fix in that thread depending on what version you're running (I'm on 7.6.1).  Looks like it's also best to make posts on the Github for the 7.6.1 (latest version) site since that one is more active, FYI!

Hope this helps everyone!

**Comment by jamesle3199** [comment]
> [DIGITALCRIMINALS#606 (comment)](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/606#issuecomment-1228024483)
> 
> This fix did it for me!! FYI the create_user.py file is located in apis/onlyfans/classes
> 
> I think most of you should be able to find a fix in that thread depending on what version you're running (I'm on 7.6.1). Looks like it's also best to make posts on the Github for the 7.6.1 (latest version) site since that one is more active, FYI!
> 
> Hope this helps everyone!

Great find, worked for me too, cheers!
