### ISSUE TITLE
get this error and schript get turns off 

### ISSUE THREAD

**Issue by Fall0n** [DIGITALCRIMINAL/UltimaScraper#1920]
turns off when I select model to get stuff from. Is there a fix for this? Have been like this for 3 days now. Its very quick cant read the error information. How can i fix this problem? i have lates zip

the way i did get screenshot is that i did film. And from video i did take the screenshot..

this is the error i get
![IMG_8851(1)](https://user-images.githubusercontent.com/59483617/186850519-9029c07a-46fd-4d4f-868c-afc707ae7de7.jpg)

can some one help me get it work..?

**Comment by yashkarangupta** [comment]
same

**Comment by Fall0n** [comment]
> same

have you find way fix the problem?

**Comment by yashkarangupta** [comment]
> > same
> 
> have you find way fix the problem?

change results["data"] to result["list"]

**Comment by yashkarangupta** [comment]
To be clear the fix is just modifying apis/onlyfans/classes/user_model.py line 283 and replace results["data"]] with results["list"]]

**Comment by Fall0n** [comment]
> To be clear the fix is just modifying apis/onlyfans/classes/user_model.py line 283 and replace results["data"]] with results["list"]]

         results = [create_highlight(x) for x in results["list"]] is my 283 and still problem

**Comment by yashkarangupta** [comment]
> > To be clear the fix is just modifying apis/onlyfans/classes/user_model.py line 283 and replace results["data"]] with results["list"]]
> 
> ```
>      results = [create_highlight(x) for x in results["list"]] is my 283 and still problem
> ```

Same message?

**Comment by Fall0n** [comment]
> > > To be clear the fix is just modifying apis/onlyfans/classes/user_model.py line 283 and replace results["data"]] with results["list"]]
> > 
> > 
> > ```
> >      results = [create_highlight(x) for x in results["list"]] is my 283 and still problem
> > ```
> 
> Same message?

what version do you use? do you still have zip file? or tell me where i can get version where i can just do that edit make it work

**Comment by Fall0n** [comment]
> I dont even have user.model.py on my classes folder. I'm using Onlyfans-7.6.1. Any help pls.

i did just try Onlyfans-7.6.1 and it have the user_model.py in classes folder

**Comment by yashkarangupta** [comment]
[OnlyFans-master.zip](https://github.com/DIGITALCRIMINAL/OnlyFans/files/9434775/OnlyFans-master.zip)

**Comment by yashkarangupta** [comment]
Hi,
Its a little complex but i can guide you.
I am creating a pdf. Will let you know once its ready.
Thanks

**Comment by LuisKingArturo** [comment]
> I dont even have user.model.py on my classes folder. I'm using Onlyfans-7.6.1. Any help pls.

I same problem

**Comment by LunarPenguin** [comment]
A quick reminder that this repo is dead/stale and if you want updates you should go [here](https://github.com/DIGITALCRIMINALS/OnlyFans)

**Comment by mdPlusPlus** [comment]
@LunarPenguin what caused the repo change?
