### ISSUE TITLE
Selected a single model but still tries to scrape every model

### ISSUE THREAD

**Issue by lowlevel80** [DIGITALCRIMINAL/UltimaScraper#1922]
So I have selected a specific model and blacklisted all the models I don't want scraping, but when the scrape of the slected model is finished it goes on to paid content then prompts me for every model on my account, een the ones I no longer follow and I have also put those in the blacklist.

e.g I choose niikkirose then am prompted for saucerie.x

Blacklisted: alexacollins
Blacklisted: rebecca_volpetti
Blacklisted: madds
Blacklisted: pearlygirlyy
Blacklisted: zenwithkris
Blacklisted: artwithkay
Choose Subscriptions: 0 = All | 1 = luciia | 2 = skylersimpson | 3 = cindy_prado | 4 = lucy_2021_x | 5 = kayla | 6 = flawlesseva26 | 7 = blonde_annavip | 8 = gabbypaige | 9 = cherrykiss | 10 = realsybilfree | 11 = realsybil | 12 = stacycruz_free | 13 = elenakamperi | 14 = truekimtylor | 15 = niikkirose | 16 = tiffany | 17 = blonde_anna | 18 = so1arkate
15
Scraping Subscriptions
Scrape Processing
Name: niikkirose
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 1.81M/1.81M [00:01<00:00, 1.10MB/s]
Type: Stories
Processing Scraped Stories
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 53/53 [00:00<00:00, 11463.98it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:00<00:00, 36081.62it/s]
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Scrape Attempt: 1/100
Processing Scraped Posts
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 328/328 [00:00<00:00, 1962.23it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 327/327 [00:00<00:00, 1335.80it/s]
Type: Archived
Type: Chats
Type: Messages
Processing Scraped Messages
100%|████████████████████████████████████████████████████████████████████████████████████████████| 1743/1743 [00:00<00:00, 3595.92it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████████████| 1109/1109 [00:00<00:00, 1572.07it/s]
Type: Highlights
Type: MassMessages
Scrape Completed

Scraping Paid Content
Scraping - luciia | 1 / 18
Scraping - skylersimpson | 2 / 18
Scraping - cindy_prado | 3 / 18
Scraping - lucy_2021_x | 4 / 18
Scraping - kayla | 5 / 18
Scraping - flawlesseva26 | 6 / 18
Scraping - blonde_annavip | 7 / 18
Scraping - gabbypaige | 8 / 18
Scraping - cherrykiss | 9 / 18
Scraping - realsybilfree | 10 / 18
Scraping - realsybil | 11 / 18
Scraping - stacycruz_free | 12 / 18
Scraping - elenakamperi | 13 / 18
Scraping - truekimtylor | 14 / 18
Scraping - niikkirose | 15 / 18
Processing Scraped Posts
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 328/328 [00:00<00:00, 533.50it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 327/327 [00:00<00:00, 1187.75it/s]
Processing Scraped Posts
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 573.74it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 327/327 [00:00<00:00, 1080.54it/s]
Processing Scraped Messages
100%|████████████████████████████████████████████████████████████████████████████████████████████| 1743/1743 [00:00<00:00, 2162.57it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████████████| 1109/1109 [00:00<00:00, 1212.59it/s]
Scraping - tiffany | 16 / 18
Scraping - blonde_anna | 17 / 18
Scraping - so1arkate | 18 / 18
Scraping Message Content
Scrape Processing
Name: saucerie.x
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts

**Comment by LunarPenguin** [comment]
Please go [here](https://github.com/DIGITALCRIMINALS/OnlyFans), this repo is dead/stale

**Comment by lowlevel80** [comment]
That's actually the one I'm using

**Comment by galagadot** [comment]
i have the same problem, so I messaged him on twitter and his solution was disable scraping message, but I just counldnt find any command to do that. So I just put every model who I dont want to scrap into blacklist, it kinda solved the problem

**Comment by LunarPenguin** [comment]
> That's actually the one I'm using

If you're using the DIGITALCRIMINALS version then i would suggest you close this issue and open a new issue there instead

**Comment by LunarPenguin** [comment]
> i have the same problem, so I messaged him on twitter and his solution was disable scraping message, but I just counldnt find any command to do that. So I just put every model who I dont want to scrap into blacklist, it kinda solved the problem

There is an option in the config to specify which media needs to be scraped, you can then specify you want all media but the messages. Have a look in the documentation for more info
