### ISSUE TITLE
0% and systematically downloads more every time I run the code.

### ISSUE THREAD

**Issue by AngryRhino69** [DIGITALCRIMINAL/UltimaScraper#1925]
Hangs at 0%. When re-running the code, more data is downloaded and then hangs. 
It initially downloads about 1.1MB/53GB.
Then goes from 1.1 MB downloaded to 3.49/53GB.
I run it a few times before giving up. Any ideas why this would happen? I initially had to manually pip install all of the dependencys.

**Comment by Scontoni** [comment]
FYI this branch is not being updated as the creator cannot access the GitHub account that owns it. The current version can be found here:
[https://github.com/DIGITALCRIMINALS/OnlyFans](https://github.com/DIGITALCRIMINALS/OnlyFans)
