### ISSUE TITLE
orjson.JSONDecodeError: unexpected control character

### ISSUE THREAD

**Issue by huguempo** [DIGITALCRIMINAL/UltimaScraper#1943]
Hi, i have this issue, can you help me to fix it please ? 

 File "/Users/XX/Downloads/OnlyFans-master/helpers/main_helper.py", line 761, in import_json
    json_file = orjson.loads(json_path.open(encoding="utf-8").read())
orjson.JSONDecodeError: unexpected control character in string: line 4 column 68 (char 111)

Thanks !

**Comment by bytadaniel** [comment]
it will work if you replace it with json.loads(open(json_path.absolute(), 'r').read(), strict=False)
