### ISSUE TITLE
Human verification - Onlyfans update

### ISSUE THREAD

**Issue by MatusLazy** [DIGITALCRIMINAL/UltimaScraper#1946]
Hi guys, 
I'm struggling with the new update from Onlyfans after the implementation of the AWS UI for human verification. 
API calls return 202 when IP is not trusted or the AI decides that I'm not human...

Did anyone find a solution for this? Using selenium/puppeteer it's working but when I call the init using an API request, I get 202 responses.

**Comment by DIGITALCRIMINALS** [comment]
They removed it for now

https://github.com/DIGITALCRIMINALS/OnlyFans/issues/695
