### ISSUE TITLE
No module named ultima_scraper_api

### ISSUE THREAD

**Issue by mrNobody1337** [DIGITALCRIMINAL/UltimaScraper#1967]
Hey @DIGITALCRIMINAL ,

Updated the script today and can't run it anymore. I get this error:
line 28, in check_config import ultima_scraper_api.helpers.main_helper as main_helper
ModuleNotFoundError: No module named 'ultima_scraper_api'

How can I fix this?

**Comment by AdhesiveMadMan** [comment]
Same issue here.

C:\Users\User\Downloads\OFscraper\OnlyFans-7.6.1>poetry run python start_us.py
Traceback (most recent call last):
  File "C:\Users\User\Downloads\OFscraper\OnlyFans-7.6.1\start_us.py", line 9, in <module>
    from ultima_scraper_api.helpers.main_helper import OptionsFormat
ModuleNotFoundError: No module named 'ultima_scraper_api'

**Comment by AdhesiveMadMan** [comment]
Found the solution! Just type this in there: poetry install

**Comment by mrNobody1337** [comment]
That doesn't work for me, I'm on linux :(

**Comment by salamihawk** [comment]
I was having the same issue. Deleted everything, redownloaded, messed everything up, got selenium errors, updated using updater.py and now I'm back to just 

`Traceback (most recent call last):
  File "/path/start_ofd.py", line 20, in <module>
    main_test.check_config()
  File "/path/tests/main_test.py", line 28, in check_config
    import ultima_scraper_api.helpers.main_helper as main_helper
ModuleNotFoundError: No module named 'ultima_scraper_api'
`

**Comment by salamihawk** [comment]
It looks like the dev messed something up. The module isn't found because it isn't there. It's called ultima_scraper, not ultima_scraper_api. Even then, tests/main_test.py is trying to import a module called helpers.main_helper, which doesn't exist either.

**Comment by salamihawk** [comment]
Looks like he updated the main script, but forgot to update ultima_scraper, maybe forgot to push it to github, since ultima-scraper has it's own page here?

**Comment by stubblesticker** [comment]
It looks like the dev messed something up. The module isn't found because it isn't there. It's called ultima_scraper, not ultima_scraper_api. Even then, tests/main_test.py is trying to import a module called helpers.main_helper, which doesn't exist either.

Looks like he updated the main script, but forgot to update ultima_scraper, maybe forgot to push it to github, since ultima-scraper has it's own page here?

**Comment by salamihawk** [comment]
Update: This is the wrong repository.

For some reason, this was forked off several months ago, the new URL is github.com/DIGITALCRIMINALS (note the S at the end). I've created a thread over there:
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/776

**Comment by stubblesticker** [comment]
Update: This is the wrong repository.

For some reason, this was forked off several months ago, the new URL is github.com/DIGITALCRIMINALS (note the S at the end). I've created a thread over there:
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/776
