### ISSUE TITLE
does this still work in 2023 getting access denied 

### ISSUE THREAD

**Issue by mallson1** [DIGITALCRIMINAL/UltimaScraper#1983]
I configured the auth file with all my onlyfans  credentials sometimes I get the download gecko driver and place it in the folder but now I am constantly getting 10 attempts and access denied any fixes in this year of 2023 or is this repo dead?

**Comment by Joe07ski** [comment]
We're in the wrong repository, he moved it a little while ago. I had forked over but my notifications still were connected to this one. Here's were he moved it to, new set of instructions. Good luck! https://github.com/DIGITALCRIMINALS/OnlyFans
