### ISSUE TITLE
Missing auth and config files

### ISSUE THREAD

**Issue by nikky78** [DIGITALCRIMINAL/UltimaScraper#1984]
Hi,
the auth.json and config.json are missing from the pckg. 
Anyone has at least an example of what those should look like please?

**Comment by Joe07ski** [comment]
We're in the wrong repository, he moved it a little while ago. I had forked over this one but my notifications were still connected to it. Here's where he moved it to, new set of instructions. Good luck! https://github.com/DIGITALCRIMINALS/OnlyFans
(The S in CRIMINALS is the difference.)
