### ISSUE TITLE
not downloading all content

### ISSUE THREAD

**Issue by deadbeatdandylyon** [DIGITALCRIMINAL/UltimaScraper#1985]
Everything seems to running well with the scrapper. however for example I downloaded from one profile which shows in total they have 431 Media. which split up they have Video (119) and Photos (312) - the photos I'm not really worried about but all 312 photos were downloaded, when I went into the video folder after downloaded complete - it only shows 88 items have been downloaded. so a total of 31 videos seems to be missing. Idk how to check to see what failed if anything did fail 

I even deleted all video files and re downloaded just to make sure and the issue occurred only 88 out of the 119 downloaded

I am using Firefox updated browser.

**Comment by tdex89** [comment]
Same issue here. Is there a fix?
