### ISSUE TITLE
Is it necessary to have the account with a credit card? And is it necessary to be subscribed to a person's premium content to be able to download it or can you download the premium content already being subscribed?

### ISSUE THREAD

**Issue by manbug10** [DIGITALCRIMINAL/UltimaScraper#1988]

**Comment by Bearded-Beard** [comment]
I don't know if you need a CC to make an account, but if you want premium content you've goto be able to pay for it somehow, and your not going to be able to bypass the buying feature on OF, you only get what you pay/subscribe for.
