### ISSUE TITLE
ujson module on windows 11 on parallels desktop for mac os

### ISSUE THREAD

**Issue by ManuJapan89** [DIGITALCRIMINAL/UltimaScraper#1990]
Hi,
i'm trying this on a win11 virtual machine on Mac os using parallels desktop(trial mode 15 days)
i have install python, pip and requirements modules but once i start ofd py
i get this error

Traceback (most recent call last):
  File "C:\OnlyFans\OnlyFans-7.6.1\start_ofd.py", line 20, in <module>
    main_test.check_config()
  File "C:\OnlyFans\OnlyFans-7.6.1\tests\main_test.py", line 21, in check_config
    import helpers.main_helper as main_helper
  File "C:\OnlyFans\OnlyFans-7.6.1\helpers\main_helper.py", line 30, in <module>
    import ujson
ImportError: DLL load failed while importing ujson: Impossibile trovare il modulo specificato.

can someone help me?
this is whaT I've installed so far on this vm

![image](https://github.com/DIGITALCRIMINAL/OnlyFans/assets/82624098/eb877cad-5b44-4da9-acb7-be181cd385e0)

many thanks

**Comment by LDkk25** [comment]
"I also encountered the same problem as you. May I ask how you resolved it?"

**Comment by ManuJapan89** [comment]
tech side solution was if i recall correctly was installing that zip i attached now and rebuild the requirements from the start. and rebuild auth.json too.
it worked.
[VC_redist.x64.zip](https://github.com/UltimaHoarder/UltimaScraper/files/14348242/VC_redist.x64.zip)

BUT, if i can help you further, and you accept it...i ended up outsourcing completely this task by joining this awesome TG group
https://t.me/Onlyfansisfree

**Comment by LDkk25** [comment]
Very much feel like I've solved this problem.
