### ISSUE TITLE
THIS REPO IS ABANDONED / UNMAINTAINED

### ISSUE THREAD

**Issue by LunarPenguin** [DIGITALCRIMINAL/UltimaScraper#1991]
This repo has been abandoned and unmaintained for years at this point.

The owner has lost access to this account and thus cant manage or archive this repo.

I keep an eye on this repo every once in a awhile and send people in the right direction, but the amount of new tickets without people searching for their problem is too damn high.

The new account of owner of the repo can be found [here](https://github.com/DIGITALCRIMINALS) but they have recently archived the successor of this repo https://github.com/DIGITALCRIMINALS/UltimaScraper/issues/983#issuecomment-1544000569.

Please **dont** post anymore tickets, they will **not** be answered and your effort will be in vain.
If you have any open tickets please **close** them and move on.

**Comment by DIGITALCRIMINAL** [comment]
It's been a long time, but I finally got my account back...

**Comment by LunarPenguin** [comment]
Thank god, you should probably archive this repo and limit issues if you dont have any further plans for this repo.

Did you just get around to getting your access back or did it really take this long?

**Comment by DIGITALCRIMINAL** [comment]
> Thank god, you should probably archive this repo and limit issues if you dont have any further plans for this repo.
> 
> Did you just get around to getting your access back or did it really take this long?

My devices were "returned" to me

**Comment by LunarPenguin** [comment]
Sounds spooky👻
