### ISSUE TITLE
Need help with initial setup

### ISSUE THREAD

**Issue by deadbeatdandylyon** [DIGITALCRIMINAL/UltimaScraper#1996]
Hello, First off I just want to say I am new to all this, I don't know the language and or coding. I was wanting to know if I may ask for some assistance with a step by step dummy guide on getting this all configured. I don't know if one exists already but I did try looking through the guide that is on the site and I'm just confused. So I hope someone may be kind enough to walk me through on setting this up correctly?

Thank you!

**Comment by LunarPenguin** [comment]
Please read #1991
