### ISSUE TITLE
How to set download to my hard disk in my profile 

### ISSUE THREAD

**Issue by Unknownn9** [DIGITALCRIMINAL/UltimaScraper#1997]
My lap storage is not enough to downlaod onlyfans content how do i set to directly download to hard disk

**Comment by LunarPenguin** [comment]
please see #1991 and to answer your question, in the `config.json` file under the `onlyfans` heading you can set `download_directories` to a path on your harddisk like this 
```json
"download_directories": [
    "E://path-to//your-hard-drive"
],

```

**Comment by Unknownn9** [comment]
where should I get config.json you can set download_directories ?? I am using Mac 

![IMG_8902](https://github.com/DIGITALCRIMINAL/OnlyFans/assets/135153468/ff75e572-23ea-4967-af58-db17df12a67c)

**Comment by LunarPenguin** [comment]
From your screenshot i get the impression that you are using a different program than the one this repo is for. Because the UI in your screenshot does not belong to this project
