### ISSUE TITLE
Please refresh the page error

### ISSUE THREAD

**Issue by Eden365** [DIGITALCRIMINAL/UltimaScraper#2003]
All of a sudden getting the error of please refresh the page? Please Help!

**Comment by fightcancer2** [comment]
Same.

**Comment by Eden365** [comment]
> 

I figured it out man!

Go to settings/config.json and on line 50 change the "dynamic_rules_link": " to this 

"https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json"

Let me know if it fixed it for you as well.

**Comment by purpleemoji** [comment]
that worked!

**Comment by DonaldTPP** [comment]
https://github.com/DIGITALCRIMINALS/UltimaScraper/issues/1024#issuecomment-1624511973

Just in case changing the one file doesn't work.

**Comment by JamiDEV** [comment]
> > 
> 
> I figured it out man!
> 
> Go to settings/config.json and on line 50 change the "dynamic_rules_link": " to this
> 
> "https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json"
> 
> Let me know if it fixed it for you as well.

worked like a charm.

**Comment by dmingledorff** [comment]
> [DIGITALCRIMINALS/UltimaScraper#1024 (comment)](https://github.com/DIGITALCRIMINALS/UltimaScraper/issues/1024#issuecomment-1624511973)
> 
> Just in case changing the one file doesn't work.

Changing all the files worked for me.
