### ISSUE TITLE
Buy you a beer

### ISSUE THREAD

**Issue by lucasff** [DIGITALCRIMINAL/UltimaScraper#361]
Please add to the README some ways to donate to you!
You're doing god's work here 👍 
maybe https://ko-fi.com/ ?

**Comment by BatmanAndWilly** [comment]
> You're doing god's work here 👍

Agreed! Maybe PayPal? I believe in leaving donations for things I use every single day.

**Comment by DIGITALCRIMINAL** [comment]
I haven't ignored this at all, but I'd rather stay anon as possible :( 

If you still would like to donate, I accept crypto donations... Thank you <3

**Comment by dilemmax** [comment]
I'd love to donate for your effort as well. How do I buy crypto currency?

**Comment by pnpninja** [comment]
350gb without any hitch - wow

**Comment by Apok6217** [comment]
works great. Thank you. also cockie helper is a great invention.

**Comment by simonchin513** [comment]
I'd like to donate in crypto, any wallet address?

**Comment by DIGITALCRIMINAL** [comment]
> I'd like to donate in crypto, any wallet address?

I do have a BTC address .-.
bc1qe80gw9yl5txdqk7aeugl07lfk08x44uh2tnzwh

**Comment by gmarcus386** [comment]
Sent from Yahoo Mail on Android 
 
  On Sat, May 29, 2021 at 1:13 AM, ***@***.***> wrote:   



I'd like to donate in crypto, any wallet address?


I do have a BTC address .-.
3HsHfrEjq7AhS3HKv7sw5MXWjEGKG11hqy

**Comment by DIGITALCRIMINAL** [comment]
> 
> 
> Sent from Yahoo Mail on Android 
>  
>   On Sat, May 29, 2021 at 1:13 AM, ***@***.***> wrote:   
> 
> 
> 
> I'd like to donate in crypto, any wallet address?
> 
> 
> I do have a BTC address .-.
> 3HsHfrEjq7AhS3HKv7sw5MXWjEGKG11hqy
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>   
> 

What happened with the response

**Comment by simonchin513** [comment]
Do you perhaps have a LTC address instead? The network fee on that is cheaper and affordable.

**Comment by DIGITALCRIMINAL** [comment]
> Do you perhaps have a LTC address instead? The network fee on that is cheaper and affordable.

Yee I do

LW4mNhYWmxQuXB3uhY7k4yXMS7mLsjTWch

Thanks

**Comment by simonchin513** [comment]
> > Do you perhaps have a LTC address instead? The network fee on that is cheaper and affordable.
> 
> Yee I do
> 
> LW4mNhYWmxQuXB3uhY7k4yXMS7mLsjTWch
> 
> Thanks

Sent some money to you on LTC, thanks for making everything free and I really appreciate what you do, will send more later when I have more to spare.

**Comment by DIGITALCRIMINAL** [comment]
> > > Do you perhaps have a LTC address instead? The network fee on that is cheaper and affordable.
> > 
> > 
> > Yee I do
> > LW4mNhYWmxQuXB3uhY7k4yXMS7mLsjTWch
> > Thanks
> 
> Sent some money to you on LTC, thanks for making everything free and I really appreciate what you do, will send more later when I have more to spare.

Thank you, I appreciate it <3
